### ISSUE TITLE
Support Ceph/RBD

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack#1]
Hi, developers

I am a IaaS engineer and I also focus on Ceph/RBD. Does ZStack support Ceph/RBD as backend storage ? Thanks ! 
And I create a QQ Group: 410185063, named "ZStack中国社区", welcome to anyone to join us. Thanks.

Best Regards,
Star Guo

**Comment by youyk** [comment]
Thanks for initializing ZStack user group in QQ!

**Comment by samos123** [comment]
would like to know the answer also...

**Comment by youyk** [comment]
Hi @samos123 , Ceph will be supported in ZStack 0.9 in this Sept. For more ZStack features plan, please find out ZStack roadmap in http://zstack.org/blog/roadmap.html

**Comment by zxwing** [comment]
this has been supported in 0.9
