### ISSUE TITLE
Delete Ceph PS won't cleanup pools 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#104]
In current zstack, when delete Ceph PS, ZStack won't delete pools. After that, if try to add the same ceph again, the VM won't be created up on it. 

The vm creation failed as:
ApiError: API call[org.zstack.header.vm.APICreateVmInstanceEvent] failed because [code: SYS.1006, description: An operation failed, details: failed to execute shell command: rbd snap create bak-t-5bfabbad1daf427b9c211b55664cc27b/813428f3d30c47cb8cad4d7111a80d1c@813428f3d30c47cb8cad4d7111a80d1c
return code: 17
stdout:
stderr: rbd: failed to create snapshot: (17) File exists
2015-08-19 19:04:29.654172 7fbdc167d7c0 -1 librbd: adding snapshot to header failed: (17) File exists

**Comment by zstackorg** [comment]
fixed in 88f905d8a04b0f3b67eefe956119c42596988c25
