### ISSUE TITLE
Update systemTags for static IP won't effect 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#106]
After VM is created with a static IP, we can't change the IP by changing System Tags and reset the VM. 

reproduce steps:
1. create VM with hostname and static IP A.
2. delete systemTags for static IP A and add a new system tag to set new static IP B.
3. stop VM and start VM
4. the VM's IP is still A.

This issue doesn't apply to hostname. We can change VM's hostname by change hostname's System Tag.

**Comment by zstackorg** [comment]
fixed in 34a832683c1d4845483f4ce6cc46712209b9c4ee
