### ISSUE TITLE
Delete Ceph PS failed: FutureCompletion timeout after 1 seconds

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#109]
Delete Ceph PS will meet follow failure:
ApiError: API call[org.zstack.header.storage.primary.APIDeletePrimaryStorageEvent] failed because [code: SYS.1004, description: Unable to delete a resource, details: FutureCompletion timeout after 1 seconds]

**Comment by zstackorg** [comment]
fixed in 5a30f132d0f66e0eab307597a5322f33c827ff1d
