### ISSUE TITLE
EIP绑了公网ip到vm上,host重启后公网ip规则出问题

### ISSUE THREAD

**Issue by vitter** [zstackorg/zstack#11]
vm和vr都在同一个host上，host重启后，vm的公网ip丢失，ssh此ip上去发现是在vr上，dettach再attach不能解决，新建一个公网ip可以绑定到vm上。版本是0.6

**Comment by youyk** [comment]
Thanks for reporting it, vitter. Better to use pure English. :)

**Comment by zstackorg** [comment]
fixed in 30462589dde2c6c71a4b76e6cb2faddbec1713f5
