### ISSUE TITLE
GetFreeIp won't return next available ip, if previous ip is used

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#110]
reproduce steps:
1. get free ip
2. use the ip to create vm as static ip
3. try to get a new free ip. it is return empty list:

>>>GetFreeIp l3NetworkUuid=7950970997164d128b7e3d8253f9913b limit=1
{
    "inventories": [],
    "success": true
}

**Comment by youyk** [comment]
If use limit =2, it will only return 1 ip:

>>>GetFreeIp l3NetworkUuid=7950970997164d128b7e3d8253f9913b limit=2
{
    "inventories": [
        {
            "gateway": "10.11.0.1",
            "ip": "10.11.0.3",
            "ipRangeUuid": "47ad684506f14716b3f5b906c283634a",
            "netmask": "255.255.0.0"
        }
    ],
    "success": true
}

**Comment by zxwing** [comment]
fixed in 8551ce89a210758669195a4fc371b4c5d5373221
