### ISSUE TITLE
Ceph mon is not cleaned up, when ceph pool is added failed

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#111]
reproduce step:
1. add ceph ps with poolnames, but the pools are not created manually.
2. add ceph ps API will failed, due to pools are not existed.
3. remove Poolname options and try to add ceph ps again.
4. PS is not able to be added. 

API call[org.zstack.header.message.APIEvent] failed because [code: SYS.1007, description: One or more API argument is invalid, details: cannot add ceph primary storage, there has been some ceph primary storage using mon[hostnames:[ceph1]]]

**Comment by zxwing** [comment]
fixed in 527db1930e7ca68e3e9138ed0c07c7ec3372aee5
