### ISSUE TITLE
attach volume might fail

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#112]
logs：

ApiError: API call[org.zstack.header.volume.APIAttachDataVolumeToVmEvent] failed because [code: VM.1005, description: Unable to attach data volume to a vm, details: failed to attach data volume[uuid:09238d1ccf974a2ca28447b537fa0cf1, installPath:ceph://pri-v-d-d71cda5e09c24cb18f1482feb1d5fe16/09238d1ccf974a2ca28447b537fa0cf1] to vm[uuid:d3a4586c876c469c92fe2b2931fe03b4, name:vlan_vm] on kvm host[uuid:c7b0d14d26dd4d109ab93f1316b70591, ip:10.10.2.241], because XmlObject has no attribute name_. missing attribute name_ in element <source>]

WARNING:kvmagent.kvmagent:XmlObject has no attribute name_. missing attribute name_ in element <source>
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/kvmagent.py", line 134, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 1512, in attach_data_volume
    vm.attach_data_volume(cmd.volume)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 574, in attach_data_volume
    self._attach_data_volume(volume)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 685, in _attach_data_volume
    attach()
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/zstacklib/utils/linux.py", line 56, in inner
    return f(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 682, in attach
    if not wait_for_attach(None):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/kvmagent/plugins/vm_plugin.py", line 668, in wait_for_attach
    if disk.source.name_ in volume.installPath:
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.7/site-packages/zstacklib/utils/xmlobject.py", line 120, in __getattr__
    raise e
AttributeError: XmlObject has no attribute name_. missing attribute name_ in element <source>

args:[(<vm_plugin.VmPlugin object at 0x2518550>,
  {'body': '{"volume":{"monInfo":[{"hostname":"ceph1","port":6789}],"secretUuid":"d57a710c-48f5-49c2-b094-dc9751c78cb4","installPath":"ceph://pri-v-d-d71cda5e09c24cb18f1482feb1d5fe16/09238d1ccf974a2ca28447b537fa0cf1","deviceId":1,"deviceType":"ceph","volumeUuid":"09238d1ccf974a2ca28447b537fa0cf1","useVirtio":true},"vmInstanceUuid":"d3a4586c876c469c92fe2b2931fe03b4"}',

```
[root@yyk-bji1 ~]# virsh dumpxml 631
<domain type='kvm' id='631'>
  <name>93b845fb5cd34759bf2470c34e4cd104</name>
  <uuid>93b845fb-5cd3-4759-bf24-70c34e4cd104</uuid>
  <description>virtualRouter.l3.0ceec849c36e4e9e8fb9ddf34f2b5e04</description>
  <metadata>
    <zstack>True</zstack>
    <internalId>2</internalId>
  </metadata>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-rhel7.0.0'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='disk' snapshot='external'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/home/local-ps/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-355aae880b78405292e2b2320d691dcb/355aae880b78405292e2b2320d691dcb.qcow2'/>
      <backingStore type='file' index='1'>
        <format type='raw'/>
        <source file='/home/local-ps/imagecache/template/bc019d35832b48058d1a8904084c47a5/bc019d35832b48058d1a8904084c47a5.qcow2'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
    <controller type='usb' index='0'>
      <alias name='usb0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='fa:be:cd:a5:30:00'/>
      <source bridge='br_eth0.102'/>
      <target dev='vnic2.0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='fa:e2:36:b4:5d:01'/>
      <source bridge='br_eth0_21'/>
      <target dev='vnic2.1'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </interface>
    <channel type='unix'>
      <source mode='bind' path='/var/lib/zstack/kvm/agentSocket/applianceVm.93b845fb5cd34759bf2470c34e4cd104'/>
      <target type='virtio' name='applianceVm.vport' state='disconnected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='5900' autoport='yes' listen='0.0.0.0'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```

**Comment by zxwing** [comment]
fixed in c5f8a43d6af5e84e254f0c9b78671066b1930f4c
