### ISSUE TITLE
VIP's IP won't be cleaned up in VR, when delete VIP for LB

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#114]
reproduce steps:
1. create vip
2. create lb on vip
3. create lb listener
4. create 2 vm and add vm nics to lb listener
5. delete vip
6. vip is deleted in Database, but if we login to VR VM, we can still see the VIP IP address in VR ifconfig.

**Comment by zxwing** [comment]
fixed in e0ba20fc16486798463de00208e1fa4f1421ea9f
