### ISSUE TITLE
Query possible bug

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#120]
If resource name is like: perf_test_0.129945944402 , the following query API won't return required resource:
QueryVmInstance name~=perf_
or QueryVmInstance name~=perf_test

But this Query API will return the right resource:
QueryVmInstance name~=perf

If we update the resource name to 'perf_test', all above Query API will return the right resource.

**Comment by zxwing** [comment]
in mysql, _ is used to match 1 character; if you want to escape it, use \_ ; see details in http://stackoverflow.com/questions/17102043/how-to-escape-underscore-in-the-string-query-in-hibernate-and-sql
