### ISSUE TITLE
New created volume doesn't exist, if original volume is deleted in ceph

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#122]
Reproduced steps:
1. create VM
2. create data volume from disk offering
3. attach data volume to VM.
4. detach data volume
5. create data volume template from data volume
6. delete data volume created in step 2
7. create data volume from data volume template, which is created in step 5
8. delete data volume tempalte
9. attach the new data volume to VM will fail:

Unable to attach data volume to a vm, details: failed to attach data volume[uuid:5e3017066bfd495db5dcd98f7f08790b, installPath:ceph://bak-t-850848dad53a44a0b9aeb4130fd77fbd/f56d498b31504806b6a94c017ee50331] to vm[uuid:b2911dda274c4739a7bd8c50a054a56b, name:virtualRouter.l3.00843d787eaa47cbae9cb88bd022dd20] on kvm host[uuid:edc0ace252b74c52a4265b3d51b43c91, ip:10.10.2.241], because unable to attach the volume[5e3017066bfd495db5dcd98f7f08790b] to vm[uuid: b2911dda274c4739a7bd8c50a054a56b], internal error: unable to execute QEMU command '__com.redhat_drive_add': could not open disk image rbd:bak-t-850848dad53a44a0b9aeb4130fd77fbd/f56d498b31504806b6a94c017ee50331:id=zstack:key=AQAUEOBViOzkDxAA1NnSV6YFA6vdtB3uRFtgJQ==:auth_supported=cephx\;none:mon_host=bji-bm-node2\:6789: Could not open 'rbd:bak-t-850848dad53a44a0b9aeb4130fd77fbd/f56d498b31504806b6a94c017ee50331:id=zstack:key=AQAUEOBViOzkDxAA1NnSV6YFA6vdtB3uRFtgJQ==:auth_supported=cephx\;none:mon_host=bji-bm-node2\:6789': No such file or directory.]

**Comment by zxwing** [comment]
fixed in a0ce2c56b1cd7c5b2776b35de36f820bfe5a3ac9
