### ISSUE TITLE
How to install zstack with offline model

### ISSUE THREAD

**Issue by 251661412** [zstackorg/zstack#124]
I want build a test enviroment , but i cant access the internet . Is there any way that i can install zstack with offline.

Thanks!!

**Comment by youyk** [comment]
Hi, if you can't access internet, you should setup intranet with yum
repository, and modify your system yum config files in /etc/yum.repo.d/*
and add local epel.repo there. ZStack installation will rely on some system
libs, which will be installed from yum repository.

And you should download zstack virtualrouter image and put it in private
http server, which could be accessed from your management node.

On Fri, Sep 11, 2015 at 10:22 AM, 251661412 <notifications@github.com>
wrote:

> I want build a test enviroment , but i cant access the internet . Is there
> any way that i can install zstack with offline.
>
> Thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/124>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Hi,  Yongkang You:
     Appreciate for you reply , by the way,  where can i download the zstack virtualrouter image ?

Thank you very much !

**Comment by 251661412** [comment]
Hi, Yongkang You:
      Appreciate for your reply !

**Comment by youyk** [comment]
Hi，

0.9 VR image URL could be found in http://zstack.org/blog/v0.9-rc2.html

On Fri, Sep 11, 2015 at 1:33 PM, 251661412 <notifications@github.com> wrote:

> Hi, Yongkang You:
> Appreciate for you reply , by the way, where can i download the zstack
> virtualrouter image ?
>
> Thank you very much !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/124#issuecomment-139457966>.
>



-- 
Yongkang You

**Comment by zxwing** [comment]
the 1.0 version has support for offline installation.
