### ISSUE TITLE
How to get the list of the account

### ISSUE THREAD

**Issue by 251661412** [zstackorg/zstack#125]
If i want to delete an account , i need to know the uuid about this account . How can I get the account information which is  in my ZStack system .
     In addition , how can i know the number of account and name in my ZStack system.

**Comment by zxwing** [comment]
There are a couple of ways to do this leveraging the query APIs. Here is an example:

>>>QueryAccount
{
    "inventories": [
        {
            "createDate": "Sep 15, 2015 9:50:19 PM",
            "lastOpDate": "Sep 15, 2015 9:50:19 PM",
            "name": "admin",
            "type": "SystemAdmin",
            "uuid": "36c27e8ff05c4780bf6d2fa65700f22e"
        }
    ],
    "success": true
}

>>>QueryAccount name=admin
{
    "inventories": [
        {
            "createDate": "Sep 15, 2015 9:50:19 PM",
            "lastOpDate": "Sep 15, 2015 9:50:19 PM",
            "name": "admin",
            "type": "SystemAdmin",
            "uuid": "36c27e8ff05c4780bf6d2fa65700f22e"
        }
    ],
    "success": true
}

>>>QueryAccount fields=uuid name=admin
{
    "inventories": [
        {
            "uuid": "36c27e8ff05c4780bf6d2fa65700f22e"
        }
    ],
    "success": true
}

>>>QueryAccount count=true
{
    "success": true,
    "total": 1
}

find more details about the query API at http://zstackdoc.readthedocs.org/en/latest/userManual/query.html

**Comment by 251661412** [comment]
Thanks zxwing

**Comment by zxwing** [comment]
I just updated the format for easy reading.
