### ISSUE TITLE
Add new host error

### ISSUE THREAD

**Issue by 251661412** [zstackorg/zstack#126]
I want add a new host, I got the error log : 
{"org.zstack.header.host.APIAddHostEvent":{"success":false,"apiId":"4c0ff4022fbc45cfa094271d52650de7","headers":{"schema":{}},"error":{"code":"HOST.1000","cause":{"code":"SYS.1000","description":"An internal error happened in system","details":"unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"pip_url\":\"http://10.X.X.92:8080/zstack/static/pypi/simple\",\"host\":\"10.X.X.93\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"10-20-14-93.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.9.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.9.tar.gz\",\"trusted_host\":\"10.X.X.92\"}'] failed\nret code: 2\nstderr: \nstdout: \nPLAY [10.X.X.93] ************************************************************ \n\nGATHERING FACTS *************************************************************** \nok: [10.X.X.93]\n\nTASK: [state epel.repo] ******************************************************* \nok: [10.X.X.93]\n\nTASK: [install epel-release yum repo] ***************************************** \nchanged: [10.X.X.93]\n\nTASK: [install epel-release] ************************************************** \nfailed: [10.X.X.93] => {\"changed\": true, \"rc\": 1, \"results\": [\"Loaded plugins: fastestmirror\\nSetting up Install Process\\nLoading mirror speeds from cached hostfile\\nCould not retrieve mirrorlist http://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=x86_64 error was\\n14: PYCURL ERROR 7 - \\\"couldn't connect to host\\\"\\n\"]}\nmsg: Error: Cannot find a valid baseurl for repo: epel-release-source\n\n\nFATAL: all hosts have already failed -- aborting\n\nPLAY RECAP 

      some error informations  seems like need i configure the host can access internet because they need use the file "epel-release-source.repo",   
       I have configure the local yum resource . why it  generate and use the file  "epel-release-source.repo"

**Comment by youyk** [comment]
Looks like your system can not connect to epel repo. Please set an epel
mirror in /etc/yum.repos.d/epel.repo


On Thu, Sep 17, 2015 at 2:37 PM, 251661412 <notifications@github.com> wrote:

> I want add a new host, I got the error log :
> {"org.zstack.header.host.APIAddHostEvent":{"success":false,"apiId":"4c0ff4022fbc45cfa094271d52650de7","headers":{"schema":{}},"error":{"code":"HOST.1000","cause":{"code":"SYS.1000","description":"An
> internal error happened in system","details":"unhandled exception happened
> when calling private void
> org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion),
> \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i
> /usr/local/zstack/ansible/hosts --private-key
> /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa
> -e '{\"pip_url\":\"
> http://10.X.X.92:8080/zstack/static/pypi/simple\",\"host\":\"10.X.X.93\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"10-20-14-93.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.9.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.9.tar.gz\",\"trusted_host\":\"10.X.X.92\"}']
> failed\nret code: 2\nstderr: \nstdout: \nPLAY [10.X.X.93]
> ************************************************************ \n\nGATHERING
> FACTS *************************************************************** \nok:
> [10.X.X.93]\n\nTASK: [state epel.repo]
> ******************************************************* \nok:
> [10.X.X.93]\n\nTASK: [install epel-release yum repo]
> ***************************************** \nchanged: [10.X.X.93]\n\nTASK:
> [install epel-release] **************************************************
> \nfailed: [10.X.X.93] => {\"changed\": true, \"rc\": 1, \"results\":
> [\"Loaded plugins: fastestmirror\nSetting up Install Process\nLoading
> mirror speeds from cached ho stfile\nCould not retrieve mirrorlist
> http://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=x86_64 error
> was\n14: PYCURL ERROR 7 - \\"couldn't connect to host\\"\n\"]}\nmsg: Error:
> Cannot find a valid baseurl for repo: epel-release-source\n\n\nFATAL: all
> hosts have already failed -- aborting\n\nPLAY RECAP
>
>   some error informations  seems like need i configure the host can access internet because they need use the file "epel-release-source.repo",
>    I have configure the local yum resource . why it  generate and use the file  "epel-release-source.repo"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/126>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Thanks youyk:
       I had set the locale repo file. The epel.repo will generate when i add the new host ,  but it seems the epel.repo need access the internet. I can't configure the host to access the internet because some security reasons .

**Comment by youyk** [comment]
Could you paste out the contents from your Host's epel.repo? If you do not
set mirrorlist, it won't access internet.

**Comment by 251661412** [comment]
Hi,youyk:
        When i want add a new host, it will generate a repo file "epel-release-source.repo" the file contents was:
         [epel-release-source]
name = epel release source package
mirrorlist = http://mirrors.fedoraproject.org/mirrorlist?repo=epel-$releasever&arch=$basearch
failovermethod = priority
enabled = 0
gpgcheck = 0

It's not enabled , So i don't understand why the error report show that use this file.


Thanks

**Comment by youyk** [comment]
When adding host, the installation process might install package from epel.
So when zstack detect /etc/yum.repos.d/epel.repo is not there, it will
install a default for you. For your case, I would suggest:
 1. remove /etc/yum.repos.d/epel*
 2. manually create your own /etc/yum.repos.d/epel.repo (if you do not
setup internal yum repo for epel, you can try to just touch an empty
epel.repo, but you might meet host adding fail later.)
 3. do yum clean metadata and try to add the host again.

On Mon, Sep 21, 2015 at 9:48 AM, 251661412 <notifications@github.com> wrote:

> Hi,youyk:
> When i want add a new host, it will generate a repo file
> "epel-release-source.repo" the file contents was:
> [epel-release-source]
> name = epel release source package
> mirrorlist =
> http://mirrors.fedoraproject.org/mirrorlist?repo=epel-$releasever&arch=$basearch
> failovermethod = priority
> enabled = 0
> gpgcheck = 0
>
> It's not enabled , So i don't understand why the error report show that
> use this file.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/126#issuecomment-141854609>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Thanks,youyk:
          Because my host can't access internet , i clean all repo files, and configure a local yum resource as "epel.repo" Then I got a new error:
          [X.X.X.X]\n\nTASK: [install dependency packages for RedHat based OS] *********************** \nfailed: [X.X.X.X] => (item=python-devel,python-setuptools,python-pip,gcc,autoconf) => {\"changed\": true, \"failed\": true, \"item\": \"python-devel,python-setuptools,python-pip,gcc,autoconf\", \"rc\": 0, \"results\": [\"Loaded plugins: fastestmirror\\nSetting up Install Process\\nLoading mirror speeds from cached hostfile\\nResolving Dependencies\\n--> Running transaction check\\n---> Package python-devel.x86_64 0:2.6.6-52.el6 will be installed\\n--> Finished Dependency Resolution\\n\\nDependencies Resolved\\n\\n================================================================================\\n Package Arch Version Repository

**Comment by youyk** [comment]
Hi,

At least the system should have correct CentOS-Base.repo to install
standard system libs.
Do you setup internal centos repository? If not, please set it up. You will
need it no matter if using ZStack. :)

On Mon, Sep 21, 2015 at 10:29 AM, 251661412 <notifications@github.com>
wrote:

> Thanks,youyk:
> Because my host can't access internet , i clean all repo files, and
> configure a local yum resource as "epel.repo" Then I got a new error:
> [X.X.X.X]\n\nTASK: [install dependency packages for RedHat based OS]
> *********************** \nfailed: [X.X.X.X] =>
> (item=python-devel,python-setuptools,python-pip,gcc,autoconf) =>
> {\"changed\": true, \"failed\": true, \"item\":
> \"python-devel,python-setuptools,python-pip,gcc,autoconf\", \"rc\": 0,
> \"results\": [\"Loaded plugins: fastestmirror\nSetting up Install
> Process\nLoading mirror speeds from cached hostfile\nResolving
> Dependencies\n--> Running transaction check\n---> Package
> python-devel.x86_64 0:2.6.6-52.el6 will be installed\n--> Finished
> Dependency Resolution\n\nDependencies
> Resolved\n\n================================================================================\n
> Package Arch Version Repository
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/126#issuecomment-141861927>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Hi,youyk:
     you mean that i need have two repo files in my host ? The one is generate from my add progress like "epel.repo" . The another is myself's configure file for the package install .
     I configure the epel.repo file content as the CentOS-Base.repo directly . Because I think the add progress can find the epel.repo and through this file to install some packages that they need .
     Need i separate the file to two files ?

**Comment by youyk** [comment]
Your configuration is fine. Could you please copy the full error logs? Or
you can manually try "yum install python-devel python-setuptools python-pip
gcc autoconf" . I thought it might be because python-pip is coming from
epel repo. So you can try to download and install python-pip manually if
not having epel repo. But I can't guarantee you won't meet any other
package issue later, without real epel repo. ;(


On Mon, Sep 21, 2015 at 11:07 AM, 251661412 <notifications@github.com>
wrote:

> Hi,youyk:
> you mean that i need have two repo files in my host ? The one is generate
> from my add progress like "epel.repo" . The another is myself's configure
> file for the package install .
> I configure the epel.repo file content as the CentOS-Base.repo directly .
> Because I think the add progress can find the epel.repo and through this
> file to install some packages that they need .
> Need i separate the file to two files ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/126#issuecomment-141865130>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Hi,Youyk:
      It seem's that I lost some package in my yum resource . I found there no package "python-pip" in the CentOS 6.6 install disk.
      How can i know which packages is necessary for the ZStack ?  Because if I can't access internet and some package lost in my local yum resource . When this happend , i just can found the current losted  package from the error report . If there lost many packages in the yum resource, how can i know it.

**Comment by youyk** [comment]
Hi,

So far we don't have a full list, for zstack package dependencies. For
example, libvirt will depends on many system libs, but we only put libvirt
in pkg depended list.

The python-pip is from epel repository, that's why you can't find it in
standard installation source.

On Mon, Sep 21, 2015 at 12:03 PM, 251661412 <notifications@github.com>
wrote:

> Hi,Youyk:
> It seem's that I lost some package in my yum resource . I found there no
> package "python-pip" in the CentOS 6.6 install disk.
> How can i know which packages is necessary for the ZStack ? Because if I
> can't access internet and some package lost in my local yum resource . When
> this happend , i just can found the current losted package from the error
> report . If there lost many packages in the yum resource, how can i know it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/126#issuecomment-141871988>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Thanks,Youyk:
       I had solve the problem .
Thans very much.
