### ISSUE TITLE
AttachPrimaryStorageToCluster failure

### ISSUE THREAD

**Issue by 251661412** [zstackorg/zstack#128]
The error infomation: 
"details": "failed to execute shell command: mount 10.X.X.X:/Primary_Storage /opt/zstack/nfsprimarystorage/prim-324b2191508e40e2a404cd17ade861a4\nreturn code: 32\nstdout: \nstderr: mount.nfs: access denied by server while mounting 10.X.X.X:/Primary_Storage\n"

It seems like the problem about authority , but there doesn't have any limit in my NFS server .
      drwxrwxrwx    2 root root  4096 Sep 22 11:42 Primary_Storage

**Comment by youyk** [comment]
Hi,

Did you manually try: mount 10.X.X.X:/Primary_Storage
/opt/zstack/nfsprimarystorage/ in your host?

On Tue, Sep 22, 2015 at 1:33 PM, 251661412 <notifications@github.com> wrote:

> The error infomation:
> "details": "failed to execute shell command: mount
> 10.X.X.X:/Primary_Storage
> /opt/zstack/nfsprimarystorage/prim-324b2191508e40e2a404cd17ade861a4\nreturn
> code: 32\nstdout: \nstderr: mount.nfs: access denied by server while
> mounting 10.X.X.X:/Primary_Storage\n"
>
> It seems like the problem about authority , but there doesn't have any
> limit in my NFS server .
> drwxrwxrwx 2 root root 4096 Sep 22 11:42 Primary_Storage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/128>.
>



-- 
Yongkang You

**Comment by 251661412** [comment]
Thanks, youyk:
       I had add the primary storage successfully through zstack ui . Everything is ok when I tried to mount the NFS server manually ,.The problem is when i want to attach a cluster for this primary storage , the error happend.

**Comment by 251661412** [comment]
I found a way that can solve this problem , vi the exports file at the NFS server. Change the client server address from a single IP to the entire network segment. 
Example:
Form : /primarystore 192.168.1.2(rw,sync)
Change to  : /primarystore 192.168.1.*(rw,sync)
But if we configure like that , there are some security problems!

**Comment by youyk** [comment]
Hi,
How about trying nfs server config like:

/primarystore 192.168.1.2(rw,sync,no_root_squash)

**Comment by 251661412** [comment]
Hi,youyk:
I can just use the entire network segment like :  /primarystore 192.168.1.*(rw,sync)

Thanks!
