### ISSUE TITLE
vnc console vm security issues?

### ISSUE THREAD

**Issue by baiyuanlab** [zstackorg/zstack#130]
Hi Sir,

I have installed two VM on public And I can via action console to connecting both vm with admin access right and then logout the zstack UI. After that I would like to use vnc to manage both VM, I can managed both vm by VNC but VNC hasn't ask me any password , is that have any security issues?

**Comment by youyk** [comment]
Hi Baiyuanlab,

Thanks for reporting this issue. We will look at it later.

**Comment by zxwing** [comment]
The KVM doesn't provide any methods to prevent accessing VM's vnc port from hosts' IP, so ZStack can do little thing on this. However, in upstream we have used iptables to forbid accesses not from host's management IP. Please use private IPs as your management IP then the VM would be safe.
