### ISSUE TITLE
New HOST-->ADD HOST issues?

### ISSUE THREAD

**Issue by baiyuanlab** [zstackorg/zstack#131]
When I create a new host and input the http://xxx.xxx.xx That will encounter /usr/local/zstack/ansible/host Please refer to picture1, the correct one is picture2

picture1
![picture 1](https://cloud.githubusercontent.com/assets/5700175/10137494/6c1902d6-662c-11e5-87d0-24715fc4ee73.png)

picture2
![picture 2](https://cloud.githubusercontent.com/assets/5700175/10137495/6c21df5a-662c-11e5-8503-46d39894ee3e.png)

**Comment by youyk** [comment]
Thanks Baiyuan! A good reporting.

**Comment by zxwing** [comment]
fixed in 11c4ce6534e25374c6214c6880cc6707555da608
