### ISSUE TITLE
Sometimes vm vnc console can not be opened 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#134]
In some case, vm console action might not be able to open. But if do the same action again, the vnc console can be opened. When the error happens, the error log is like:

{
  "org.zstack.header.console.APIRequestConsoleAccessEvent": {
    "success": false,
    "apiId": "75fb62da9e434b1fbc54846f30c59125",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "SYS.1006",
      "description": "An operation failed",
      "details": "failed to execute shell command: python -c \"from zstacklib.utils import log; import websockify; log.configure_log('/var/log/zstack/consoleProxy/192_168_230_159-5901-f9da50eee8d14a4e8964e1a344121721'); websockify.websocketproxy.websockify_init()\" 192.168.230.160:51922 -D --target-config=/var/lib/zstack/consoleProxy/192_168_230_159-5901 --idle-timeout=60\nreturn code: 1\nstdout: \nstderr: WebSocket server settings:\n  - Listen on 192.168.230.160:51922\n  - Flash security policy server\n  - No SSL/TLS support (no cert file)\n  - Backgrounding (daemon)\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/var/lib/zstack/virtualenv/consoleproxy/lib/python2.7/site-packages/websockify/websocketproxy.py\", line 419, in websockify_init\n    server.start_server()\n  File \"/var/lib/zstack/virtualenv/consoleproxy/lib/python2.7/site-packages/websockify/websocket.py\", line 909, in start_server\n    tcp_keepintvl=self.tcp_keepintvl)\n  File \"/var/lib/zstack/virtualenv/consoleproxy/lib/python2.7/site-packages/websockify/websocket.py\", line 698, in socket\n    sock.bind(addrs[0][4])\n  File \"/usr/lib64/python2.7/socket.py\", line 224, in meth\n    return getattr(self._sock,name)(*args)\nsocket.error: [Errno 99] Cannot assign requested address\n"
    },
    "id": "aefc3dcba6fd42e1addf455d7637592b",
    "creatingTime": 1444495445209
  }
}

**Comment by zxwing** [comment]
unable to reproduce this bug. We have made some changes in the vnc consoleproxy, which makes the whole process more clearer. Please reopen if it happens again, and paste the output of "ps aux | grep python" on the management server.
