### ISSUE TITLE
can that NoVNC in Browser dispaly the "vm hostname"? 

### ISSUE THREAD

**Issue by baiyuanlab** [zstackorg/zstack#137]
can that NoVNC in Browser dispaly t
he "vm hostname"? When we using zstack management UI.

current show out the states please refer to attached picture 001. Thanks
![001](https://cloud.githubusercontent.com/assets/5700175/10444991/4124368a-719f-11e5-8e04-2a6f5dcaf810.png)

**Comment by youyk** [comment]
Tracked in https://github.com/zstackorg/zstack-dashboard/issues/58 . So close this issue.
