### ISSUE TITLE
VM hardware resource states disappear after changing new offering

### ISSUE THREAD

**Issue by baiyuanlab** [zstackorg/zstack#138]
in Zstack manahement the VM hardware resource states is empty now, I thought that would be show some hardware resource information such as CPU usage, harddisk,memory.........

current states please refer to attached picture. Thank

![004](https://cloud.githubusercontent.com/assets/5700175/10445233/58939ac4-71a2-11e5-9f75-594853890e48.png)
![005](https://cloud.githubusercontent.com/assets/5700175/10445234/58d22c26-71a2-11e5-820c-90eefc28551c.png)

**Comment by youyk** [comment]
Does it happen after change VM's offering?

**Comment by baiyuanlab** [comment]
Yes. this happen after change VM's offering

**Comment by youyk** [comment]
This bug looks like a UI bug only. The VM Instance data structure is correct, when doing queryvminstance operation in zstack-cli.

**Comment by zxwing** [comment]
this is handled by the new UI. Open it if it's still found in the new UI
