### ISSUE TITLE
Get host local storage capacity

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#142]
In local storage scenario, the primary storage capacity is per host. So the cluster storage capacity or zone storage capacity can not reflect the real capacity in some host. 

GetPrimaryStorageCapacity 
all=                  clusterUuids=         primaryStorageUuids=
timeout=              zoneUuids=            

So we'd better to create a new API **GetLocalPrimaryStorageCapacity hostUuid = **

**Comment by zxwing** [comment]
new API is added: GetLocalStorageHostDiskCapacity, fixed in upstream
