### ISSUE TITLE
deploydb unable to clean schema

### ISSUE THREAD

**Issue by zxwing** [zstackorg/zstack#144]
造成这问题的原因是我机器里的 MySQL 在安装过程被升级了，我 Google 了下关于 MySQL 升级的问题

找到我 log 里一样的错误   -- > Cannot proceed because system tables used by Event Scheduler were found damaged at server start。

查看手册得到 --> 当你更新到新版本MySQL，你应同时更新系统表，以确保它们的结构最新

手动 做了检查及升级后,  重起  mysqld 
mysqlcheck -u root -p --all-databases --check-upgrade --auto-repair
mysql_upgrade -u root -p
/etc/init.d/mysql restart

Clean schema zstack 那地方就正常了

考虑到使用者可能会有类似情形, 是否要把这几个步骤 加到 deploydb.sh 里 
(  不知道能不能检查 MySQL 曾经升级过, 来决定要不要做那几个指令,    对于这个我是外行的 )

**Comment by youyk** [comment]
能强制做这几步吗？就是不管升级与否

2015-10-24 1:56 GMT+08:00 zxwing <notifications@github.com>:

> 造成这问题的原因是我机器里的 MySQL 在安装过程被升级了，我 Google 了下关于 MySQL 升级的问题
>
> 找到我 log 里一样的错误 -- > Cannot proceed because system tables used by Event
> Scheduler were found damaged at server start。
>
> 查看手册得到 --> 当你更新到新版本MySQL，你应同时更新系统表，以确保它们的结构最新
>
> 手动 做了检查及升级后, 重起 mysqld
> mysqlcheck -u root -p --all-databases --check-upgrade --auto-repair
> mysql_upgrade -u root -p
> /etc/init.d/mysql restart
>
> Clean schema zstack 那地方就正常了
>
> 考虑到使用者可能会有类似情形, 是否要把这几个步骤 加到 deploydb.sh 里
> ( 不知道能不能检查 MySQL 曾经升级过, 来决定要不要做那几个指令, 对于这个我是外行的 )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/144>.
>



-- 
Yongkang You

**Comment by heidsoft** [comment]
应该可以的

**Comment by zxwing** [comment]
already took a note of this
