### ISSUE TITLE
unable to start vm with qemu option "cache=none" when file system not support O_DIRECT

### ISSUE THREAD

**Issue by mattyen** [zstackorg/zstack#146]
I use zfs pool as a localStorage for zstack on my machine, and zstack unable to start vm while I new VmInstance.
Please see API failure response below.

{
  "org.zstack.header.vm.APICreateVmInstanceEvent": {
    "success": false,
    "apiId": "ffdbd4c1a92c4705b5ef4217ca25af51",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "SYS.1006",
      "cause": {
        "code": "HOST.1005",
        "description": "Failed to start vm on hypervisor",
        "details": "failed to start vm[uuid:e6153a68fbf745018814a453a50d4d8c name:virtualRouter.l3.a9c1fe71cbbd438dab7937233397109c] on kvm host[uuid:6c69abf8581b4a81b99511b8ea6f4e46, ip:192.168.2.99], because unable to start vm[uuid:e6153a68fbf745018814a453a50d4d8c, name:virtualRouter.l3.a9c1fe71cbbd438dab7937233397109c], libvirt error: internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=none: file system may not support O_DIRECT\nqemu-system-x86_64: -drive file=/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=none: could not open disk image /DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2: Could not open '/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2': Invalid argument\n"
      },
      "description": "An operation failed",
      "details": "failed to start vm[uuid:e6153a68fbf745018814a453a50d4d8c name:virtualRouter.l3.a9c1fe71cbbd438dab7937233397109c] on kvm host[uuid:6c69abf8581b4a81b99511b8ea6f4e46, ip:192.168.2.99], because unable to start vm[uuid:e6153a68fbf745018814a453a50d4d8c, name:virtualRouter.l3.a9c1fe71cbbd438dab7937233397109c], libvirt error: internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=none: file system may not support O_DIRECT\nqemu-system-x86_64: -drive file=/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=none: could not open disk image /DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2: Could not open '/DataRaidz/nfs_root/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-cc41ec605b43458abfd2f7236e03e50b/cc41ec605b43458abfd2f7236e03e50b.qcow2': Invalid argument\n"
    },
    "id": "2dcfd5742e104ed7a6785d9eb86d9cef",
    "creatingTime": 1445861649816
  }
}

**Comment by youyk** [comment]
Thanks reporting bugs. This is a good catching!

**Comment by youyk** [comment]
Fixed and closed.
