### ISSUE TITLE
在vm中执行init 0或者关机操作的时候 系统资源无法及时回收

### ISSUE THREAD

**Issue by snailyang** [zstackorg/zstack#147]
前提系统资源使用较满
1 已经使用的vm 以linux举例 执行init 0操作
2 vm 正常关机
3 约3秒后 UI中 vm状态 显示stoped
4 在UI中 对这个关闭的vm 执行 Start 操作 会报资源不足
等待时间 可能在几分钟之后 有一定几率  无法启动vm
----
临时解决方案  在host页面将主机 reconnect 后，正常启动关闭的vm

**Comment by youyk** [comment]
Thanks for reporting bug @snailyang . From QQ discussion, when VM starting failed, it might report:  No enough resource.

**Comment by ryuzen85** [comment]
althrough vm is power off, but zstack does not it. zstack think vm is stopped but not destroyed, so resource is keeped.
In case, if vm restart again, that will cause resource race condition.
so my opinion is destroy the vm manually.

**Comment by youyk** [comment]
We will fix it in 1.0. ZStack dynamically monitor vm status and sync to
database.

On Fri, Nov 13, 2015 at 4:23 PM, RyuZen <notifications@github.com> wrote:

> althrough vm is power off, but zstack does not it. zstack think vm is
> stopped but not destroyed, so resource is keeped.
> In case, if vm restart again, that will cause resource race condition.
> so my opinion is destroy the vm manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/147#issuecomment-156360301>.
>



-- 
Yongkang You

**Comment by zxwing** [comment]
fixed in upstream
