### ISSUE TITLE
New instance button calls Admin api, so that common account can not new vm.

### ISSUE THREAD

**Issue by ryuzen85** [zstackorg/zstack#150]
login as a normal account, can not new vm instance, althrough has image,l3,instance offering resources. Because new instance button calls Admin api?

**Comment by youyk** [comment]
Thanks for reporting this issue. This is current UI limitation. Should be fixed in zstack-dashboard in the future by support different account login.

**Comment by zxwing** [comment]
this is a feature request for UI. change the label to enhancement

**Comment by zxwing** [comment]
a new bug https://github.com/zstackorg/zstack/issues/182 is created for this
