### ISSUE TITLE
install.sh can not get management interface,without default route rule

### ISSUE THREAD

**Issue by ryuzen85** [zstackorg/zstack#151]
install.sh need default network route rule, if there is no default, it can not get management interface.
at line 12. "MANAGEMENT_INTERFACE=`ip route | grep default | cut -d ' ' -f 5`", it need default route rule.

**Comment by youyk** [comment]
Yes. If installer doesn't detect default route, it will exit and ask user to provide device by -I option:

ip addr show $MANAGEMENT_INTERFACE >/dev/null 2>&1
if [ $? -ne 0 ];then
    ip addr show |grep $MANAGEMENT_INTERFACE |grep inet >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "$MANAGEMENT_INTERFACE is not a recognized IP address or network interface name. Please assign correct IP address by '-I MANAGEMENT_NODE_IP_ADDRESS'" 
        exit 1
    fi

We also made a fix for this issue to set default management node IP address in https://github.com/zstackorg/zstack-utility/commit/6f7dddb7b705ef5df5158b4d177726a8b8117d6d 

This patch will be picked in zstack 1.0

**Comment by youyk** [comment]
If installer didn't find the default router, it will request user to provide the right network device and Ip address for zstack management node to listen on.

**Comment by zstackorg** [comment]
Fixed and close it
