### ISSUE TITLE
If management node ip is private ip, console proxy can not display in browser

### ISSUE THREAD

**Issue by ryuzen85** [zstackorg/zstack#152]
my management node ip is private network ip, so consoleproxy shows private ip too.
my management node has public ip too.
so if I access zstack ui from public network in web browser,  the vm web console can not display.

**Comment by ryuzen85** [comment]
zstack-ctl configure consoleProxyOverriddenIp=PUBLIC_IP
Then restart management service is ok

**Comment by ryuzen85** [comment]
zstack-ctl configure consoleProxyOverriddenIp=PUBLIC_IP
Then restart management service is ok

**Comment by youyk** [comment]
Yes. consoleProxyOverriddenIp is the right configuration. It is recorded in http://zstack.org/cn/documentation/faq.html
