### ISSUE TITLE
addimage always timeout , used the local http server 

### ISSUE THREAD

**Issue by cenxinxing** [zstackorg/zstack#154]
>>>
>>>AddImage name=VIRTUAL-ROUTER format=qcow2 mediaType=RootVolumeTemplate platform=Linux url=http://103.30.54.208:8089/zstack-virtualrouter-0.9.0.qcow2 backupStorageUuids=9b574c3a7287468d81b7c13cb29b4378
API call[org.zstack.header.image.APIAddImageEvent] failed because [code: SYS.1002, description: Unable to create a resource, details: Failed to download image[name:VIRTUAL-ROUTER] on all backup storage[9b574c3a7287468d81b7c13cb29b4378]. 
error code for backup storage[uuid:9b574c3a7287468d81b7c13cb29b4378]: ErrorCode [code = SYS.1001, description = A message or a operation timeout, details = Message[org.zstack.header.storage.backup.DownloadImageMsg] timeout after 1800 seconds]]
API call[org.zstack.header.image.APIAddImageEvent] failed because [code: SYS.1002, description: Unable to create a resource, details: Failed to download image[name:VIRTUAL-ROUTER] on all backup storage[9b574c3a7287468d81b7c13cb29b4378]. 
error code for backup storage[uuid:9b574c3a7287468d81b7c13cb29b4378]: ErrorCode [code = SYS.1001, description = A message or a operation timeout, details = Message[org.zstack.header.storage.backup.DownloadImageMsg] timeout after 1800 seconds]]

I used the local http server and addimage image-ttylinux succeed , but when addimage(zstack-virtualrouter-0.9.0.qcow2), it always timeout failed , I test write on the backupStorage, it's ok.

why set the timeout is 1800s?

how can avoid this problem? thank you

**Comment by youyk** [comment]
On Thu, Nov 19, 2015 at 4:20 PM, cenxinxing <notifications@github.com>
wrote:

> http://103.30.54.208:8089/zstack-virtualrouter-0.9.0.qcow2


It shouldn't be slow, if you put it in local http server.

Can you try to run "wget
http://103.30.54.208:8089/zstack-virtualrouter-0.9.0.qcow2" in backstorage
server?


-- 
Yongkang You

**Comment by cenxinxing** [comment]
The problem is solved.

just restart the local http server like nginxl.

thank you

**Comment by cenxinxing** [comment]
why you don't support the local image when addimage.

like file=/home/xxx.qcow2

**Comment by youyk** [comment]
Will support in  1.0. ;)

On Fri, Nov 20, 2015 at 11:09 AM, cenxinxing <notifications@github.com>
wrote:

> why you don't support the local image when addimage.
>
> like file=/home/xxx.qcow2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/154#issuecomment-158266278>.
>



-- 
Yongkang You

**Comment by cenxinxing** [comment]
when i add the secend Backup Storage,  it was failed. what is the mean?

the path which i add to Backup Storage is a dir with ext3 .

REQUEST
{
  "org.zstack.storage.backup.sftp.APIAddSftpBackupStorageMsg": {
    "hostname": "103.30.54.208",
    "username": "root",
    "password": "root",
    "type": "SftpBackupStorage",
    "resourceUuid": "01153b288b214d41a76b7521e9ab3052",
    "name": "BACKUP-STORAGE2",
    "description": null,
    "url": "/home/BACKUP-STORAGE2/aa",
    "session": {
      "uuid": "982ac4c8d723463783ee52b2d7c92220"
    }
  }
}

RESPONSE
{
  "org.zstack.header.message.APIEvent": {
    "success": false,
    "apiId": "3e630b76cacd45f29eb13b0ad8773e71",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "SYS.1007",
      "description": "One or more API argument is invalid",
      "details": "existing SimpleHttpBackupStorage with hostname[103.30.54.208] found"
    },
    "id": "6e9f4f1a1eb44beeb6e94fa427126e9b",
    "creatingTime": 1447989817639
  }
}

**Comment by cenxinxing** [comment]
the dir which add to  Backup Storage must support nfs?

**Comment by youyk** [comment]
The same backup storage server can not be added twice.

SimpleHttpBackupStorage with hostname[103.30.54.208] found

On Fri, Nov 20, 2015 at 11:36 AM, cenxinxing <notifications@github.com>
wrote:

> the dir which add to Backup Storage must support nfs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/154#issuecomment-158269656>.
>



-- 
Yongkang You
