### ISSUE TITLE
add primary-stprage use NFS , but capacity info wasn't report.

### ISSUE THREAD

**Issue by cenxinxing** [zstackorg/zstack#158]
i install two manager host, used the centos7 os. it have question appear.

could you tell me to see which log .

question 1:
add primary-stprage use NFS , but capacity info wasn't report.

DESCRIPTION: 	
STATE: 	Enabled
STATUS: 	Connected
TYPE: 	NFS
URL: 	103.30.54.209:/usr/local/zstack/nfs_root
TOTAL CAPACITY: 	0
AVAILABLE CAPACITY: 	0
UUID: 	5c4a320505084230ad799b0d43826059
ZONE UUID: 	28a996db406544aab1b65ccd8844a7d8
CREATED DATE: 	Nov 25, 2015 10:09:00 PM
LAST UPDATED DATE: 	Nov 25, 2015 10:09:00 PM

question 1:
i add host2 , but status alway Connecting.

DESCRIPTION: 	
STATE: 	Enabled
STATUS: 	Connecting
HYPERVISOR: 	KVM
HOST IP: 	103.30.54.210
UUID: 	67c2f9da5fa84d77840d81078214610e
CLUSTER UUID: 	69d3b11e7af742aa8d94566595dd0f25
ZONE UUID: 	28a996db406544aab1b65ccd8844a7d8

CREATED DATE: 	Nov 26, 2015 1:18:31 AM
LAST UPDATED DATE: 	Nov 26, 2015 1:18:31 AM

host2 once restart in the past time. and i start the node have some error info

[root@centos01 home]# zstack-ctl start_node
successfully started Tomcat container; now it's waiting for the management node ready for serving APIs, which may take a few seconds
ERROR: no management-node-ready message received within 120 seconds, please check error in log file /usr/local/zstack/apache-tomcat/webapps/zstack/../../logs/management-server.log

**Comment by cenxinxing** [comment]
[management-server.log.txt](https://github.com/zstackorg/zstack/files/44686/management-server.log.txt)

**Comment by youyk** [comment]
For NFS PS capacity, you need to attach it to a cluster, then you can get
the capacity.

For host2 is in starting stage, make sure host2 yum.repo is setting
correctly. Host in starting means it is installing kvmagent. kvmagent need
to check system libs status from yum (including epel). So make sure yum
update works perfectly in host. From management node log, it seems your
host is not able to be ssh:

2015-11-26 01:55:19,594 WARN  [Ssh] (zs-thread-18) exec ssh command: md5sum
/var/lib/zstack/kvm/zstacklib-0.9.tar.gz, exception
[host:103.30.54.210, port:22, user:root, timeout:2147483647]

Is your firewall enabled or ssh port changed?

On Thu, Nov 26, 2015 at 3:05 PM, cenxinxing <notifications@github.com>
wrote:

> i install two manager host, used the centos7 os. it have question appear.
>
> could you tell me to see which log .
>
> question 1:
> add primary-stprage use NFS , but capacity info wasn't report.
>
> DESCRIPTION:
>
> STATE: Enabled
> STATUS: Connected
> TYPE: NFS
> URL: 103.30.54.209:/usr/local/zstack/nfs_root
> TOTAL CAPACITY: 0
> AVAILABLE CAPACITY: 0
> UUID: 5c4a320505084230ad799b0d43826059
> ZONE UUID: 28a996db406544aab1b65ccd8844a7d8
> CREATED DATE: Nov 25, 2015 10:09:00 PM
> LAST UPDATED DATE: Nov 25, 2015 10:09:00 PM
>
> question 1:
> i add host2 , but status alway Connecting.
>
> DESCRIPTION:
>
> STATE: Enabled
> STATUS: Connecting
> HYPERVISOR: KVM
> HOST IP: 103.30.54.210
> UUID: 67c2f9da5fa84d77840d81078214610e
> CLUSTER UUID: 69d3b11e7af742aa8d94566595dd0f25
> ZONE UUID: 28a996db406544aab1b65ccd8844a7d8
>
> CREATED DATE: Nov 26, 2015 1:18:31 AM
> LAST UPDATED DATE: Nov 26, 2015 1:18:31 AM
>
> host2 once restart in the past time. and i start the node have some error
> info
>
> [root@centos01 home]# zstack-ctl start_node
> successfully started Tomcat container; now it's waiting for the management
> node ready for serving APIs, which may take a few seconds
> ERROR: no management-node-ready message received within 120 seconds,
> please check error in log file
> /usr/local/zstack/apache-tomcat/webapps/zstack/../../logs/management-server.log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/158>.
>



-- 
Yongkang You

**Comment by cenxinxing** [comment]
the question was resolved , thank you.

a new question:

i created a new volume and attach to vm , i can see it  create and attach to vm successful , but i login in the vm and use 'fdisk -l' to see all the volume , i can't see the volume , but after a moment i can see it , what is the reason?

**Comment by youyk** [comment]
Which OS version your VM used? The ttylinux kernel doesn't support volume
live attach/detach. You need to use CentOS or Ubuntu.

BTW, please close this issue and open new one, since the discussion is not
related with the title. ;)

On Mon, Nov 30, 2015 at 2:50 PM, cenxinxing <notifications@github.com>
wrote:

> the question was resolved , thank you.
>
> a new question:
>
> i created a new volume and attach to vm , i can see it create and attach
> to vm successful , but i login in the vm and use 'fdisk -l' to see all the
> volume , i can't see the volume , but after a moment i can see it , what is
> the reason?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/158#issuecomment-160539436>.
>



-- 
Yongkang You

**Comment by cenxinxing** [comment]
ok , the vm OS is Ubuntu.

i closed this issue now, thank you.

**Comment by youyk** [comment]
On Mon, Nov 30, 2015 at 4:14 PM, cenxinxing <notifications@github.com>
wrote:

> ok , the vm OS is Ubuntu.


You can try with dmesg or lspci to check if the disk is really added.


-- 
Yongkang You
