### ISSUE TITLE
how to install the computer node ?

### ISSUE THREAD

**Issue by cenxinxing** [zstackorg/zstack#159]
I have been isntalled two manager node , now i want to install the compute node which will add to host in the future , but i don't know how to do it , it is all node in zstack is manager node?

**Comment by youyk** [comment]
On Thu, Nov 26, 2015 at 4:52 PM, cenxinxing <notifications@github.com>
wrote:

> ed two manager node , now i want to install the compute node which will
> add to host in the future , but i don't know how to do it , it is all node
> in zstack is manag


For  general Host, it just needs to do it from UI, Host -> Add. Or from
zstack-cli, AddKvmHost


-- 
Yongkang You

**Comment by cenxinxing** [comment]
it need install zstack before Host -> Add ?

**Comment by cenxinxing** [comment]
REQUEST
{
  "org.zstack.kvm.APIAddKVMHostMsg": {
    "username": "root",
    "password": "root",
    "name": "HOST3",
    "description": null,
    "clusterUuid": "69d3b11e7af742aa8d94566595dd0f25",
    "managementIp": "103.30.54.206",
    "session": {
      "uuid": "6f49b59f1656410595b8a4338c8f8bab"
    }
  }
}

RESPONSE
{
  "org.zstack.header.host.APIAddHostEvent": {
    "success": false,
    "apiId": "9064fb7ca49b40acbf3a8808bb325470",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "HOST.1000",
      "cause": {
        "code": "SYS.1000",
        "description": "An internal error happened in system",
        "details": "unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"pip_url\":\"http://103.30.54.210:8080/zstack/static/pypi/simple\",\"host\":\"103.30.54.206\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"103-30-54-206.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.9.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.9.tar.gz\",\"trusted_host\":\"103.30.54.210\"}'] failed\nret code: 2\nstderr: \nstdout: \nPLAY [103.30.54.206] ********************************************************** \n\nGATHERING FACTS *************************************************************** \nok: [103.30.54.206]\n\nTASK: [state epel.repo] ******************************************************* \nok: [103.30.54.206]\n\nTASK: [install libselinux-python, since next step might use it.] ************** \nok: [103.30.54.206] => (item=libselinux-python)\n\nTASK: [install epel-release yum repo] ***************************************** \nchanged: [103.30.54.206]\n\nTASK: [install epel-release] ************************************************** \nchanged: [103.30.54.206]\n\nTASK: [enable epel repository] ************************************************ \nok: [103.30.54.206]\n\nTASK: [install dependency packages for RedHat based OS] *********************** \nfailed: [103.30.54.206] => (item=python-devel,python-setuptools,python-pip,gcc,autoconf) => {\"failed\": true, \"item\": \"python-devel,python-setuptools,python-pip,gcc,autoconf\"}\nmsg: Error from repoquery: ['/usr/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '-q', '--qf', '%{name}-%{version}-%{release}.%{arch}', 'python-devel']: Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again\nCould not match packages: Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again\n\n\nFATAL: all hosts have already failed -- aborting\n\nPLAY RECAP ******************************************************************** \n           to retry, use: --limit @/root/kvm.yaml.retry\n\n103.30.54.206              : ok=6    changed=2    unreachable=0    failed=1   \n\n"
      },
      "description": "Unable to add host",
      "details": "unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"pip_url\":\"http://103.30.54.210:8080/zstack/static/pypi/simple\",\"host\":\"103.30.54.206\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"103-30-54-206.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.9.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.9.tar.gz\",\"trusted_host\":\"103.30.54.210\"}'] failed\nret code: 2\nstderr: \nstdout: \nPLAY [103.30.54.206] ********************************************************** \n\nGATHERING FACTS *************************************************************** \nok: [103.30.54.206]\n\nTASK: [state epel.repo] ******************************************************* \nok: [103.30.54.206]\n\nTASK: [install libselinux-python, since next step might use it.] ************** \nok: [103.30.54.206] => (item=libselinux-python)\n\nTASK: [install epel-release yum repo] ***************************************** \nchanged: [103.30.54.206]\n\nTASK: [install epel-release] ************************************************** \nchanged: [103.30.54.206]\n\nTASK: [enable epel repository] ************************************************ \nok: [103.30.54.206]\n\nTASK: [install dependency packages for RedHat based OS] *********************** \nfailed: [103.30.54.206] => (item=python-devel,python-setuptools,python-pip,gcc,autoconf) => {\"failed\": true, \"item\": \"python-devel,python-setuptools,python-pip,gcc,autoconf\"}\nmsg: Error from repoquery: ['/usr/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '-q', '--qf', '%{name}-%{version}-%{release}.%{arch}', 'python-devel']: Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again\nCould not match packages: Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again\n\n\nFATAL: all hosts have already failed -- aborting\n\nPLAY RECAP ******************************************************************** \n           to retry, use: --limit @/root/kvm.yaml.retry\n\n103.30.54.206              : ok=6    changed=2    unreachable=0    failed=1   \n\n"
    },
    "id": "2864937256b8455499134831cdf303cd",
    "creatingTime": 1448527628128
  }
}

**Comment by youyk** [comment]
No. It doesn't need to add any service in host manually. ZStack
installation is like a single software. Hosts are just needed add from
zstack management node. ZStack will handle all required libs installation.
User only need to make sure yum repos are correctly setting in Hosts.

On Fri, Nov 27, 2015 at 9:40 AM, cenxinxing <notifications@github.com>
wrote:

> it need install zstack before Host -> Add ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/159#issuecomment-160017207>.
>



-- 
Yongkang You

**Comment by youyk** [comment]
On Fri, Nov 27, 2015 at 9:43 AM, cenxinxing <notifications@github.com>
wrote:

> Cannot retrieve metalink for repository: epel/x86_64


Cannot retrieve metalink for repository: epel/x86_64

--> This means your host /etc/yum.repo.d/epel.repo setting is not correct.
Please fix it before add host again.


-- 
Yongkang You

**Comment by cenxinxing** [comment]
it's ok, thank you.

**Comment by cenxinxing** [comment]
have a question:

on the cli , http proxy is not availability. it mean ,i can't get the image from your http server.

**Comment by youyk** [comment]
Yeah. Please download it manually and set up local http server.

On Fri, Nov 27, 2015 at 3:01 PM, cenxinxing <notifications@github.com>
wrote:

> have a question:
>
> on the cli , http proxy is not availability. it mean ,i can't get the
> image from your http server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/159#issuecomment-160055676>.
>



-- 
Yongkang You
