### ISSUE TITLE
two question want to ask , thank you.

### ISSUE THREAD

**Issue by cenxinxing** [zstackorg/zstack#161]
quesion1 : 

i created a new volume and attach to vm which OS is ubuntu, i can see it create and attach
to vm successful from web_ui, but i login in the vm and use 'fdisk -l' to see all the
volume , i can't see the volume , but after a moment i can see it , why?

quesion 2:

How the manager cluster work? The manage cluster suport HA? 

I installed a zstack cluster which have two manager node in accordance with your instructions,  I think the multi management node is to increase the reliability of the cluster, so i login in web_ui by manager node2 ip and port , but i can't login in, the log info on manager node2 is like this : 

log_path :  /var/log/zstack/zstack-ui.log

add request[id:dd04a6920eea45078db39ded43f8a5fc]
DEBUG:zstack_dashboard.web:add request[id:dd04a6920eea45078db39ded43f8a5fc]
sent message: {"org.zstack.header.identity.APILogInByAccountMsg": {"headers": {"replyTo": "zstack.ui.message.c7c8dde46f73462ba3ea06ae6d17ae20", "noReply": "false", "correlationId": "dd04a6920eea45078db39ded43f8a5fc"}, "serviceId": "api.portal", "password": "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86", "id": "dd04a6920eea45078db39ded43f8a5fc", "accountName": "admin"}}
DEBUG:zstack_dashboard.web:sent message: {"org.zstack.header.identity.APILogInByAccountMsg": {"headers": {"replyTo": "zstack.ui.message.c7c8dde46f73462ba3ea06ae6d17ae20", "noReply": "false", "correlationId": "dd04a6920eea45078db39ded43f8a5fc"}, "serviceId": "api.portal", "password": "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86", "id": "dd04a6920eea45078db39ded43f8a5fc", "accountName": "admin"}}

**Comment by zxwing** [comment]
github is not a good place to ask questions. If you speak Chinese, please join the QQ group 410185063 where people dicuss ZStack. If you only speak English, please ask questions in Google group https://groups.google.com/forum/#!forum/zstack
