### ISSUE TITLE
cannot  delete host after the Host IP changed

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack#169]
after the host IP changed, the relative guest status changed to unknown, and the Host changed to Disconnected. whether the Host is in enabled or disabled status, delete the host, the error happens,
and host is still there

{
  "success": false,
  "apiId": "c8daa8a4e91c4ff38d917e1c52d484d2",
  "headers": {
    "schema": {}
  },
  "session": {
    "callid": "zs-ke98mcpY",
    "uuid": "7d81d95121d745fe83973cb59af56f0f"
  },
  "error": {
    "code": "SYS.1004",
    "cause": {
      "code": "VM.1002",
      "cause": {
        "code": "SYS.1006",
        "description": "An operation failed",
        "details": "host[uuid:7d8443a3ab454f6494f95ce04de57286, name:carl-1] is in status[Disconnected], cannot perform required operation"
      },
      "description": "Unable to stop a vm",
      "details": "host[uuid:7d8443a3ab454f6494f95ce04de57286, name:carl-1] is in status[Disconnected], cannot perform required operation"
    },
    "description": "Unable to delete a resource",
    "details": "host[uuid:7d8443a3ab454f6494f95ce04de57286, name:carl-1] is in status[Disconnected], cannot perform required operation"
  },
  "id": "db06126737c64a8cae91c5d5a735825e",
  "creatingTime": 1449974086348

**Comment by zxwing** [comment]
fixed in #167 . after change the password, you need to reconnect the host. Once the host reconnected, you can delete the vms
