### ISSUE TITLE
it fails to install the rabbitmq during installing the zstack

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack#174]
while installing the zstack by "./zizhu-installer-centos7-1.0-A4-U3.bin -o" on centos7.1 mininal x86_64, it always fails to install the rabbitmq,
and reports "cannot detect command to enable service rabbitmq-server, typo or init system potentially unknown"

partial log:
Install Rabbitmq Server:
PLAY [192.168.0.110] **********************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.0.110]

TASK: [pre-install script] ****************************************************
changed: [192.168.0.110]

TASK: [set RHEL7 yum repo] ****************************************************
changed: [192.168.0.110]

TASK: [set RHEL6 yum repo] ****************************************************
skipping: [192.168.0.110]

TASK: [install RabbitMQ on RedHat OS from local] ******************************
skipping: [192.168.0.110]

TASK: [install RabbitMQ on RedHat OS from online] *****************************
changed: [192.168.0.110]

TASK: [install RabbitMQ on Ubuntu OS] *****************************************
skipping: [192.168.0.110]

TASK: [open 5672 port] ********************************************************
changed: [192.168.0.110]

TASK: [open 5673 port] ********************************************************
changed: [192.168.0.110]

TASK: [open 15672 port] *******************************************************
changed: [192.168.0.110]

TASK: [enable RabbitMQ] *******************************************************
failed: [192.168.0.110] => {"failed": true, "parsed": false}
{"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": "initctl version", "rc": 2}^M
{"msg": "cannot detect command to enable service rabbitmq-server, typo or init system potentially unknown", "failed": true}^M

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/tmp.qXt0asqsvn.retry

192.168.0.110              : ok=7    changed=6    unreachable=0    failed=1

^[[31mERROR: see prior Ansible log for detailed information
Ansible failure
^[[0m^[[31mFAIL
^[(B^[[m
^[[31m  Reason: failed to install rabbitmq server.

The detailed installation log could be found in /tmp/zstack_installation.log

**Comment by zxwing** [comment]
yyk has fixed this in upstream
