### ISSUE TITLE
if create instance in bunch with the request resouce over the system pool,only one vm could start successfully

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack#177]
如果批量新建虚拟机的数量超过系统可承受的资源，在启动虚拟机时，系统只有一个虚拟机创建成功，但是系统可用的资源应该启动三个虚拟机。
free -m显示系统可用内存为971M，不够启动超过两个虚拟机。
应该是系统相应的cache被占用，没有释放，导致虚拟机不可启动。

虚拟机启动之前资源显示：
资源名	总容量	可用容量	可用容量比例
处理器	6796 MHZ	6284 MHZ	92.46%
内存	2.78 G	2.28 G	82.02%
主存储	889.56 G	886.2 G	99.62%
镜像服务器	889.56 G	886.19 G	99.62%
主存储实际使用量	889.56 G	886.63 G	99.66%
IP地址	21	20	95.23%

free -m
 total        used        free      shared  buff/cache   available
Mem:           2847         971         722           4        1153        1668
Swap:         10239           3       10236

**Comment by lstfyt** [comment]
如果执行echo 3 > /proc/sys/vm/drop_caches  ，内存可以释放，但是批量创建依然fail。
[root@mevoco-1 zstack]# echo 3 > /proc/sys/vm/drop_caches
[root@mevoco-1 zstack]# free -m
              total        used        free      shared  buff/cache   available
Mem:           2847         949        1784           4         114        1766
Swap:         10239           3       10236



{
  "success": false,
  "apiId": "f402dd27b5bc45b8b2fe9b29c6cf3a56",
  "headers": {
    "schema": {}
  },
  "session": {
    "callid": "zs-Gb8tu6Vx",
    "uuid": "d4189098d26a4865a54f4d43fdfc5743"
  },
  "error": {
    "code": "SYS.1006",
    "cause": {
      "code": "SYS.1006",
      "description": "An operation failed",
      "details": "failed to execute shell command: BR_NAME=\"br_eth0\"\nDHCP_IP=\"192.168.0.130\"\nDHCP_NETMASK=\"255.255.255.0\"\n\nBR_NUM=`ip link show $BR_NAME | grep $BR_NAME | cut -d\":\" -f1`\nOUTER_DEV=\"outer$BR_NUM\"\nINNER_DEV=\"inner$BR_NUM\"\n\nexit_on_error() {\n    [ $? -ne 0 ] && exit 1\n}\n\nip netns list | grep \"^$BR_NAME$\" > /dev/null\nif [ $? -ne 0 ]; then\n    ip netns add $BR_NAME\n    exit_on_error\nfi\n\n# in case the namespace deleted and the orphan outer link leaves in the system,\n# deleting the orphan link and recreate it\nip netns exec $BR_NAME ip link | grep $INNER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n   ip link del $OUTER_DEV &> /dev/null\nfi\n\nip link | grep $OUTER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    ip link add $OUTER_DEV type veth peer name $INNER_DEV\n    exit_on_error\n    ip link set $OUTER_DEV up\n    exit_on_error\nfi\n\nbrctl show $BR_NAME | grep $OUTER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    brctl addif $BR_NAME $OUTER_DEV\n    exit_on_error\nfi\n\nip netns exec $BR_NAME ip link | grep $INNER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    ip link set $INNER_DEV netns $BR_NAME\n    exit_on_error\nfi\n\nip netns exec $BR_NAME ip addr show $INNER_DEV | grep $DHCP_IP > /dev/null\nif [ $? -ne 0 ]; then\n    ip netns exec $BR_NAME ip addr flush dev $INNER_DEV\n    exit_on_error\n    ip netns exec $BR_NAME ip addr add $DHCP_IP/$DHCP_NETMASK dev $INNER_DEV\n    exit_on_error\n    ip netns exec $BR_NAME ip link set $INNER_DEV up\n    exit_on_error\nfi\n\nBR_PHY_DEV=`brctl show $BR_NAME  | grep $BR_NAME | sed 's/\\s\\s*/ /g' | cut -d' ' -f4`\nif [ x$BR_PHY_DEV == \"x\" ]; then\n   echo \"cannot find the physical interface of the bridge $BR_NAME\"\n   exit 1\nfi\n\nebtables-save | grep \"FORWARD -p ARP -o $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p ARP -o $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\n    exit_on_error\nfi\n\nebtables-save | grep \"FORWARD -p ARP -i $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p ARP -i $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\n    exit_on_error\nfi\n\nebtables-save | grep \"FORWARD -p IPv4 -o $BR_PHY_DEV --ip-proto udp --ip-sport 67:68 -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p IPv4 -o $BR_PHY_DEV --ip-proto udp --ip-sport 67:68 -j DROP\n    exit_on_error\nfi\n\nexit 0\nreturn code: 1\nstdout: \nstderr: Cannot create namespace file \"/var/run/netns/br_eth0\": File exists\n"
    },
    "description": "An operation failed",
    "details": "failed to execute shell command: BR_NAME=\"br_eth0\"\nDHCP_IP=\"192.168.0.130\"\nDHCP_NETMASK=\"255.255.255.0\"\n\nBR_NUM=`ip link show $BR_NAME | grep $BR_NAME | cut -d\":\" -f1`\nOUTER_DEV=\"outer$BR_NUM\"\nINNER_DEV=\"inner$BR_NUM\"\n\nexit_on_error() {\n    [ $? -ne 0 ] && exit 1\n}\n\nip netns list | grep \"^$BR_NAME$\" > /dev/null\nif [ $? -ne 0 ]; then\n    ip netns add $BR_NAME\n    exit_on_error\nfi\n\n# in case the namespace deleted and the orphan outer link leaves in the system,\n# deleting the orphan link and recreate it\nip netns exec $BR_NAME ip link | grep $INNER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n   ip link del $OUTER_DEV &> /dev/null\nfi\n\nip link | grep $OUTER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    ip link add $OUTER_DEV type veth peer name $INNER_DEV\n    exit_on_error\n    ip link set $OUTER_DEV up\n    exit_on_error\nfi\n\nbrctl show $BR_NAME | grep $OUTER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    brctl addif $BR_NAME $OUTER_DEV\n    exit_on_error\nfi\n\nip netns exec $BR_NAME ip link | grep $INNER_DEV > /dev/null\nif [ $? -ne 0 ]; then\n    ip link set $INNER_DEV netns $BR_NAME\n    exit_on_error\nfi\n\nip netns exec $BR_NAME ip addr show $INNER_DEV | grep $DHCP_IP > /dev/null\nif [ $? -ne 0 ]; then\n    ip netns exec $BR_NAME ip addr flush dev $INNER_DEV\n    exit_on_error\n    ip netns exec $BR_NAME ip addr add $DHCP_IP/$DHCP_NETMASK dev $INNER_DEV\n    exit_on_error\n    ip netns exec $BR_NAME ip link set $INNER_DEV up\n    exit_on_error\nfi\n\nBR_PHY_DEV=`brctl show $BR_NAME  | grep $BR_NAME | sed 's/\\s\\s*/ /g' | cut -d' ' -f4`\nif [ x$BR_PHY_DEV == \"x\" ]; then\n   echo \"cannot find the physical interface of the bridge $BR_NAME\"\n   exit 1\nfi\n\nebtables-save | grep \"FORWARD -p ARP -o $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p ARP -o $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\n    exit_on_error\nfi\n\nebtables-save | grep \"FORWARD -p ARP -i $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p ARP -i $BR_PHY_DEV --arp-ip-dst $DHCP_IP -j DROP\n    exit_on_error\nfi\n\nebtables-save | grep \"FORWARD -p IPv4 -o $BR_PHY_DEV --ip-proto udp --ip-sport 67:68 -j DROP\" > /dev/null\nif [ $? -ne 0 ]; then\n    ebtables -I FORWARD -p IPv4 -o $BR_PHY_DEV --ip-proto udp --ip-sport 67:68 -j DROP\n    exit_on_error\nfi\n\nexit 0\nreturn code: 1\nstdout: \nstderr: Cannot create namespace file \"/var/run/netns/br_eth0\": File exists\n"
  },
  "id": "164a87f5534c4e80abdf150d5ae5233a",
  "creatingTime": 1450970431461

**Comment by zxwing** [comment]
this is fixed by yyk in upstream
