### ISSUE TITLE
system memory didn't change after increase the memory to the host

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack#181]
对计算节点增加CPU 或者内存后，点击计算节点重连，系统可用内存 并未发生变化。
而且CPU的显示应该以个数xCPU频率为好。

系统显示：
处理器	27184 MHZ	26492 MHZ	97.45%
内存	2.78 G	1.86 G	67.04%

计算节点显示：
[root@mevoco-1 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           5812        1247        4163           8         401        4344
Swap:         10239           0       10239

**Comment by zxwing** [comment]
fixed in fa3c5f2f40b064b36709d45ba39838c89424bb11
