### ISSUE TITLE
primary storage capacity allocation and counting bug

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#19]
When primary storage does not have enough space and multiple VMs are creating at the same time, some VM will be created successfully, some will be failed. The failed log is as:

API call[org.zstack.header.vm.APICreateVmInstanceEvent] failed because [code: SYS.1006, description: An operation failed, details: after subtracting reserved capacity[1G], there is no primary storage having required size[209715200 bytes]]

The issues are : 
1. the PS capacity is not changed at this moment 
2. we can continue to try to create multiple VMs again. Same numbers of VMs will be created like the 1st time, and the failed VM has same failed log. This parallel VMs creating operation (fixed number of VMs are created success and the rest failed) could be kept doing for many times. 

The next picture show the PS capacity is not changed. 

![screen shot 2015-05-01 at 23 59 56](https://cloud.githubusercontent.com/assets/2962014/7432833/435162f6-f05e-11e4-8895-c6e47e1d0fa0.png)

The execution script is like:

cat test.sh
#!/bin/bash
zstack-cli LogInByAccount accountName=admin password=password
max_times=20
times=0
while [ $times -lt $max_times ]; do
    zstack-cli CreateVmInstance name=VM+$times instanceOfferingUuid=af36372ace294399a6c56eb62af95020 imageUuid=1aa945dfdc004cdca7cb0a1ffd8b1acd l3NetworkUuids=096a7c294ec146febb1c645205ea99db &
    times=`expr $times + 1`
done

In every execution cycle, 8 VMs (VM root volume is 200M) will be created. 12 VMs failed.

**Comment by youyk** [comment]
@zxwing please take a look. 
Thanks cooper found this issue firstly.

**Comment by zxwing** [comment]
2f3a456aa91e895d34047de81af5188ed187e2e7
