### ISSUE TITLE
安装第二个节点的时候，报解压pypi的错误

### ISSUE THREAD

**Issue by cist** [zstackorg/zstack#195]
TASK: [untar pypi] ************************************************************ 
failed: [192.168.2.161] => {"changed": true, "cmd": "cd /tmp/; tar jxf /tmp/pypi.tar.bz", "delta": "0:00:00.206149", "end": "2016-01-13 14:39:26.463352", "rc": 2, "start": "2016-01-13 14:39:26.257203", "warnings": []}
stderr: 
bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/tmp.o5EcLoZSjr.retry

**Comment by youyk** [comment]
please 'rm -rf  /usr/local/zstack/apache-tomcat/webapps/zstack/static/
pypi.tar.bz' in management-node 1. The issue might be happened after
breaking the command when doing zstack-ctl install_management_node.

On Wed, Jan 13, 2016 at 4:01 PM, cist <notifications@github.com> wrote:

> TASK: [untar pypi]
> ************************************************************
> failed: [1921682161] => {"changed": true, "cmd": "cd /tmp/; tar jxf
> /tmp/pypitarbz", "delta": "0:00:00206149", "end": "2016-01-13
> 14:39:26463352", "rc": 2, "start": "2016-01-13 14:39:26257203", "warnings":
> []}
> stderr:
> bzip2: Compressed file ends unexpectedly;
> perhaps it is corrupted? *Possible* reason follows
> bzip2: Inappropriate ioctl for device
> Input file = (stdin), output file = (stdout)
>
> It is possible that the compressed file(s) have become corrupted
> You can use the -tvv option to test integrity of such files
>
> You can use the `bzip2recover' program to attempt to recover
> data from undamaged sections of corrupted files
>
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
>
> FATAL: all hosts have already failed -- aborting
>
> PLAY RECAP
> ********************************************************************
> to retry, use: --limit @/root/tmpo5EcLoZSjrretry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/195>.
>



-- 
Yongkang You

**Comment by youyk** [comment]
Any feedback?

**Comment by cist** [comment]
thanks  i resolved it   .  thanks very much
