### ISSUE TITLE
passing ec2 style user-data when initializing a vm

### ISSUE THREAD

**Issue by Cad** [zstackorg/zstack#2]
Could we add support for providing user-data to vm instances as similarly done with ec2?

**Comment by youyk** [comment]
Thanks for submitting feature request. We do plan to support similar functions to compatible with EC2.

**Comment by zxwing** [comment]
1.0 has supported cloud-init

**Comment by zxwing** [comment]
1.0 has userdata support

**Comment by Cad** [comment]
Many thanks! 👍
