### ISSUE TITLE
Unable to add host code: HOST.1000 details: [Async Http Timeout]

### ISSUE THREAD

**Issue by judi0713** [zstackorg/zstack#200]
I do the same step by [Flat Network](http://zstack.org/cn/tutorials/flat-network-cli.html)
But when i use the command line to add host.
It says
```>>>AddKVMHost name=HOST1 managementIp=10.211.55.20 username=root password=j clusterUuid=954737580c8c471da6e3d13cfe6ce2e3```

```API call[org.zstack.header.host.APIAddHostEvent] failed because [code: HOST.1000, description: Unable to add host, details: [Async Http Timeout] url: http://10.211.55.20:7070/host/fact, timeout after 300[SECONDS], command: {}]```
```API call[org.zstack.header.host.APIAddHostEvent] failed because [code: HOST.1000, description: Unable to add host, details: [Async Http Timeout] url: http://10.211.55.20:7070/host/fact, timeout after 300[SECONDS], command: {}]```

When I tap the "http://10.211.55.20:7070/host/fact" in my brower,it appear 404 Not Found.

**Comment by youyk** [comment]
Please check if there is Call Trace in /var/log/zstack/zstack-kvmagent.log.

**Comment by youyk** [comment]
@judi0713 any feedback?

**Comment by zxwing** [comment]
close as no detailed information provided

**Comment by judi0713** [comment]
@youyk i reinstall ,laterly it goes well

**Comment by youyk** [comment]
Great. Thanks for update. @judi0713
