### ISSUE TITLE
org.zstack.header.host.APIAddHostEvent failed

### ISSUE THREAD

**Issue by pingliu** [zstackorg/zstack#209]
I follow theFlat Network Provider  tutorial，
when I add host ,it's failed

the log is 
{"org.zstack.header.host.APIAddHostEvent":{"apiId":"0d421a736e2d4b32a913cb21cd20d899","success":false,"error":{"code":"HOST.1000","description":"Unable to add host","details":"unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e \u0027{\"init\":\"true\",\"hostname\":\"10-0-17-78.zstack.org\",\"pkg_kvmagent\":\"kvmagent-1.0.tar.gz\",\"trusted_host\":\"10.0.17.78\",\"yum_repo\":\"\\\"alibase,aliupdates,aliextras,aliepel\\\"\",\"host\":\"10.0.17.78\",\"pip_url\":\"http://10.0.17.78:8080/zstack/static/pypi/simple\",\"zstack_root\":\"/var/lib/zstack/\",\"yum_server\":\"10.0.17.78:8080\",\"pkg_zstacklib\":\"zstacklib-1.0.tar.gz\"}\u0027] failed\nret code: 2\nstderr:  [WARNING]: Consider using yum module rather than running yum\n [WARNING]: Consider using yum module rather than running rpm\n\nstdout: \nPLAY ***************************************************************************\n\nTASK [setup]

**Comment by pingliu** [comment]
the password is correct, and I Flush the iptables.
please help me, thanks

**Comment by youyk** [comment]
@pingliu, the error log is not full.  It didn't show the real reason. How
did you install ZStack? Did you use option like " -R aliyun" ? Usually the
AddHost error is due to system libs installation error through yum. So if
you are in China, please use aliyun yum repo.

On Wed, Feb 17, 2016 at 8:17 PM, pingliu <notifications@github.com> wrote:

> the password is correct, and I Flush the iptables.
> please help me, thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/209#issuecomment-185175324>.
>



-- 
Yongkang You

**Comment by pingliu** [comment]
@youyk  I use aliyun. do you have a wechat num. 
we can communicate with wechat.

**Comment by pingliu** [comment]
@youyk i use aliyun. the log cannnot find which libs error
can we use wechat communicate??
![image](https://cloud.githubusercontent.com/assets/6415493/13133853/8eb2aaf8-d63a-11e5-9892-6ce551ebaab8.png)

**Comment by youyk** [comment]
hi @pingliu, could you help to run following command in your zstack
management node and paste the output here.

ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i
/usr/local/zstack/ansible/hosts --private-key
/usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa
-e '{"init":"true","hostname":"10-0-17-78.zstack.org
","pkg_kvmagent":"kvmagent-1.0.tar.gz","trusted_host":"10.0.17.78","yum_repo":""alibase,aliupdates,aliextras,aliepel"","host":"10.0.17.78","pip_url":"
http://10.0.17.78:8080/zstack/static/pypi/simple
","zstack_root":"/var/lib/zstack/","yum_server":"10.0.17.78:8080
","pkg_zstacklib":"zstacklib-1.0.tar.gz"}'

On Thu, Feb 18, 2016 at 12:24 PM, pingliu <notifications@github.com> wrote:

> @youyk <https://github.com/youyk> i use aliyun. the log cannnot find
> which libs error
> can we use wechat communicate??
> [image: image]
> <https://cloud.githubusercontent.com/assets/6415493/13133853/8eb2aaf8-d63a-11e5-9892-6ce551ebaab8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/209#issuecomment-185537217>.
>



-- 
Yongkang You

**Comment by pingliu** [comment]
the result is

ERROR! Syntax Error while loading YAML.


The error appears to have been in '<string>': line 2, column 81, but may
be elsewhere in the file depending on the exact syntax problem.

**Comment by zstackorg** [comment]
Join our QQ group 410185063, lots of users asking questions there

**Comment by youyk** [comment]
This issue should be resolved. @pingliu I will close it currently. If you still meet it, please report a new one.
