### ISSUE TITLE
[0.7-preview] Can not create guest vm from ISO image with iSCSI on Btrfs

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack#21]
I just test zstack 0.7-preview version, and I try to create guest vm from ISO image but it fails:

{"org.zstack.header.vm.APICreateVmInstanceMsg":{"name":"VM1","description":null,"instanceOfferingUuid":"8dc33e6ae39a45f3968b3170185cfea5","imageUuid":"50952352b1fe483b9b9ad07370739da2","l3NetworkUuids":["eeb9feff031243f2ae4928c3f3882ad6"],"rootDiskOfferingUuid":"aa995c8e171b4e39aa3e7b7b85ccd18e","dataDiskOfferingUuids":[],"zoneUuid":null,"clusterUuid":null,"hostUuid":null,"resourceUuid":"b1d10ea8b02b40818686768abe42e196","defaultL3NetworkUuid":"eeb9feff031243f2ae4928c3f3882ad6","systemTags":["hostname::vm1"],"session":{"uuid":"b3000cee427549d494ed0b706a3ea219"}}}

the resault is :
{"org.zstack.header.vm.APICreateVmInstanceEvent":{"success":false,"apiId":"1394b85890964031aca6d7e6a084b8e5","headers":{"schema":{}},"error":{"code":"SYS.1006","cause":{"code":"SYS.1000","description":"An internal error happened in system","details":"unhandled exception happened when calling private void org.zstack.kvm.KVMHost.startVm(org.zstack.header.vm.VmInstanceSpec, org.zstack.header.message.NeedReplyMessage, org.zstack.header.core.NoErrorCompletion), null"},"description":"An operation failed","details":"unhandled exception happened when calling private void org.zstack.kvm.KVMHost.startVm(org.zstack.header.vm.VmInstanceSpec, org.zstack.header.message.NeedReplyMessage, org.zstack.header.core.NoErrorCompletion), null"},"id":"062aa8552c7b481aa088cb33d6369aeb","creatingTime":1430834985652}}

**Comment by zxwing** [comment]
fixed in mainline
