### ISSUE TITLE
UI rabbitmq 没有 （failover）自动故障切换功能

### ISSUE THREAD

**Issue by syuanwei** [zstackorg/zstack#215]
当rabbitmq服务器有多台运行时（mq0,mq1,mq2）,CloudBus.serverIp.0指定的服务器突然故障，UI将不会自动切换到正常的mq1,mq2,导致UI无法登陆

**Comment by youyk** [comment]
Thanks for reporting. It is a bug.

**Comment by youyk** [comment]
Fixed in ZStack 1.2
