### ISSUE TITLE
[0.7-preview] Can not boot ttylinux from iSCSI on Btrfs 

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack#22]
I just test zstack 0.7-preview and found that ttylinux cannot boot from iSCSI on Btrfs. However. VR boots and works well. I guess ttylinux does not support SCSI storage controller.

Running lspci on VR as bellow:
![iscsi](https://cloud.githubusercontent.com/assets/2645213/7475902/e409c500-f37c-11e4-81e3-a8951539dd99.png)

**Comment by zxwing** [comment]
not a ZStack but.
