### ISSUE TITLE
yum clean metadata应该改为yum clean --enablerepo=alibase metadata

### ISSUE THREAD

**Issue by quarkonics** [zstackorg/zstack#225]
因为在ansible部署组件过程中，我们会禁用alibase和aliepel之类的repo，如果用户正好也没有enable其他的repo，这样会导致yum clean metadata失败

**Comment by youyk** [comment]
fixed by https://github.com/zstackorg/zstack-utility/commit/96e887878c285633692927cb7b94aebf88b6506a
