### ISSUE TITLE
开发环境搭建错误

### ISSUE THREAD

**Issue by liu2972505** [zstackorg/zstack#234]
最新版本maven无法编译通过了，包括测试用例，有自定义包缺失。

**Comment by youyk** [comment]
Can you share the building failure?

**Comment by zxwing** [comment]
把        <module>test</module>
        <module>premium</module>
从pom.xml文件中去掉即可以编译

**Comment by zxwing** [comment]
我把它去掉了，你pull最新的即可以编译

**Comment by liu2972505** [comment]
test从pom.xml里边去掉maven可以通过，可是执行测试用例的mvn test -Dtest=test_case_name还会提示Could not find artifact org.zstack:mevoco:jar:1.0.0 ，这个如何解决，现在的test和mevoco好像结合的太紧密了
