### ISSUE TITLE
无法迁移虚拟机，通过virsh命令正常迁移，错误信息"details": "failed to migrate vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] from kvm host[uuid:cf53af7b292a46da8bc5b38cd9d0d989, ip:zstack03] to dest host[ip:zstack04], unable to migrate vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] to qemu+tcp://zstack04/system, 不支持的参数：migration URI is not supported by tunnelled migration"

### ISSUE THREAD

**Issue by wxy-x** [zstackorg/zstack#243]
无法迁移虚拟机，通过virsh命令正常迁移，错误信息"details": "failed to migrate vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] from kvm host[uuid:cf53af7b292a46da8bc5b38cd9d0d989, ip:zstack03] to dest host[ip:zstack04], unable to migrate vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] to qemu+tcp://zstack04/system, 不支持的参数：migration URI is not supported by tunnelled migration"

**Comment by youyk** [comment]
Yes. This is a bug in CentOS7.2 . We have reported this to RedHat. In
ZStack 1.1, we will make a work around to fix it.

On Wed, Mar 23, 2016 at 9:49 AM, wxy-x <notifications@github.com> wrote:

> 无法迁移虚拟机，通过virsh命令正常迁移，错误信息"details": "failed to migrate
> vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] from kvm
> host[uuid:cf53af7b292a46da8bc5b38cd9d0d989, ip:zstack03] to dest
> host[ip:zstack04], unable to migrate
> vm[uuid:750ceebc3a5e4e4790a47623ba0205c7] to qemu+tcp://zstack04/system,
> 不支持的参数：migration URI is not supported by tunnelled migration"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/243>
>



-- 
Yongkang You

**Comment by wxy-x** [comment]
thanks
