### ISSUE TITLE
希望解释一下 为什么用SSHJ 而没有采用Ganymed SSH-2

### ISSUE THREAD

**Issue by cullenx** [zstackorg/zstack#248]
希望解释一下 为什么用SSHJ 而没有采用Ganymed SSH-2
技术选型后 看中哪一点

**Comment by zxwing** [comment]
没有特别的原因，SSHJ是我以前就用过的库，比较熟悉，所以就直接选了它。

**Comment by zxwing** [comment]
没有特别的原因，SSHJ是我以前就用过的库，比较熟悉，所以就直接选了它。
