### ISSUE TITLE
Error:0 unable to connect to MySQL

### ISSUE THREAD

**Issue by DDbang** [zstackorg/zstack#251]
It's my first time to use ZStack,when I type 'sudo zstack-ctl start',it stop at 'Starting ZStack management node, it may take a few minutes...' when i type ^C,it show this error,how can i solve this problem???

**Comment by zxwing** [comment]
What ZStack version did you use? you can use 'sudo zstack-ctl -v start' that will print detailed info to the screen so you can debug

**Comment by youyk** [comment]
Hi, please upgrade to ZStack 1.2 to see if it fixed.
