### ISSUE TITLE
关于zstack的Host要求

### ISSUE THREAD

**Issue by xdsnet** [zstackorg/zstack#254]
在Zstack组建私有云的各类教程中，对Host（物理机）的介绍几乎都没有，望能补充相关内容。

**Comment by ghxandsky** [comment]
@xdsnet 请问想了解Host哪方面内容？

**Comment by xdsnet** [comment]
就是Host（物理机） 配置要求，还有如何安装基本系统、基础组件等等

**Comment by youyk** [comment]
The host configuration depends on how many VMs will be run on Host. 
There is a data center deployment recommendation in http://www.mevoco.com/downloads/mevoco/documents/PD3001-Mevoco-Data-Center-Setup-1.0.0.pdf

But if you are just running a private cloud, 8 CPUs with 32GB memory and 2T hard driver is a minimal requirement .
