### ISSUE TITLE
zstack创建虚拟机报错

### ISSUE THREAD

**Issue by test01011** [zstackorg/zstack#259]
大神！请问我创建云主机时出现以下报错：no host found in clusters that has attached to L2Networks which have L3Networks , 请问是什么原因呢？

**Comment by youyk** [comment]
The most possible reason is your L2 Network is not attached to any cluster. Please click L2 and check if it is attached to cluster. Or you didn't create a L3 Network on it.

Please join ZStack QQ group to get directly support. 410185063

**Comment by test01011** [comment]
OK！Thank you very much！
