### ISSUE TITLE
add ubuntu 14.04 server host failed

### ISSUE THREAD

**Issue by cadsimula-xin** [zstackorg/zstack#271]
Does zstack require cent os?

the response message is:

"org.zstack.header.host.APIAddHostEvent":{"success":false,"apiId":"bde0d3e2b6244b85bafe0d3082b056ed","headers":{"schema":{}},"error":{"code":"HOST.1000","cause":{"code":"SYS.1000","description":"An internal error happened in system","details":"unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo PYTHONPATH=/usr/local/zstack/ansible/files/zstacklib python /usr/local/zstack/ansible/kvm.py -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"pip_url\":\"http://192.168.1.193:8080/zstack/static/pypi/simple\",\"host\":\"192.168.1.194\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"192-168-1-194.zstack.org\",\"pkg_zstacklib\":\"zstacklib-1.2.tar.gz\",\"pkg_kvmagent\":\"kvmagent-1.2.tar.gz\",\"**yum_server**\":\"192.168.1.193:8080\",\"trusted_host\":\"192.168.1.193\"}'] failed\nret code: 1\nstderr: \nstdout: [ HOST: 192.168.1.194 ] ERROR: pip install package /var/lib/zstack//pip-7.0.3.tar.gz failed! [ cost 459ms to finish ]\nDetail: [ HOST: 192.168.1.194 ] ERROR: \n\n:stderr: \nUsage: \n pip install [options] <requirement specifier> ...\n pip install [options] -r <requirements file> ...\n pip install [options] [-e] <vcs project url> ...\n pip install [options] [-e] <local project path> ...\n pip install [options] <archive url/path> ...\n\nno such option: --disable-pip-version-check\n\n[ HOST: 192.168.1.194 ] ERROR: pip install package virtualenv failed! [ cost 465ms to finish ]\nDetail: [ HOST: 192.168.1.194 ] ERROR: \n\n:stderr: \nUsage: \n pip install [options] <requirement specifier> ...\n pip install [options] -r <requirements file> ...\n pip install [options] [-e] <vcs project url> ...\n pip install [options] [-e] <local project path> ...\n pip install [options] <archive url/path> ...\n\nno such option: --disable-pip-version-check\n\n"},"description":"Unable to add host","details":"unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo PYTHONPATH=/usr/local/zstack/ansible/files/zstacklib python /usr/local/zstack/ansible/kvm.py -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"pip_url\":\"http://192.168.1.193:8080/zstack/static/pypi/simple\",\"host\":\"192.168.1.194\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"192-168-1-194.zstack.org\",\"pkg_zstacklib\":\"zstacklib-1.2.tar.gz\",\"pkg_kvmagent\":\"kvmagent-1.2.tar.gz\",\"yum_server\":\"192.168.1.193:8080\",\"trusted_host\":\"192.168.1.193\"}'] failed\nret code: 1\nstderr: \nstdout: [ HOST: 192.168.1.194 ] ERROR: pip install package /var/lib/zstack//pip-7.0.3.tar.gz failed! [ cost 459ms to finish ]\nDetail: [ HOST: 192.168.1.194 ] ERROR: \n\n:stderr: \nUsage: \n pip install [options] <requirement specifier> ...\n pip install [options] -r <requirements file> ...\n pip install [options] [-e] <vcs project url> ...\n pip install [options] [-e] <local project path> ...\n pip install [options] <archive url/path> ...\n\nno such option: --disable-pip-version-check\n\n[ HOST: 192.168.1.194 ] ERROR: pip install package virtualenv failed! [ cost 465ms to finish ]\nDetail: [ HOST: 192.168.1.194 ] ERROR: \n\n:stderr: \nUsage: \n pip install [options] <requirement specifier> ...\n pip install [options] -r <requirements file> ...\n pip install [options] [-e] <vcs project url> ...\n pip install [options] [-e] <local project path> ...\n pip install [options] <archive url/path> ...\n\nno such option: --disable-pip-version-check\n\n"},"type":{"_name":"key.event.API.API_EVENT"},"id":"37ea4600e7b54611ab69421d9fb7a169","crea

**Comment by youyk** [comment]
Looks like the system has wrong pip version, which leads the error:　**no such option: --disable-pip-version-check**

Could you try ZStack 1.3 RC: http://zstack.org/cn_blog/v1.3-rc1.html

**Comment by winger007** [comment]
This issue has been fixed by commit: 04bd0e89

**Comment by winger007** [comment]
This commit belong to zstack-utility:
https://github.com/zstackorg/zstack-utility/commit/04bd0e89
