### ISSUE TITLE
add login ip:port in zstack-ctl status

### ISSUE THREAD

**Issue by robertlinux** [zstackorg/zstack#285]
Otherwise, there is no easier way to know how to login when there are multiple nics.

**Comment by robertlinux** [comment]
zstack-ctl start doesn't show that either

**Comment by youyk** [comment]
zstack-ui URL will be shown in zstack-ctl status in 1.4 release.

**Comment by youyk** [comment]
zstack-ctl start and start_ui will also show the URL to access zstack
