### ISSUE TITLE
zstack 身份认证权限

### ISSUE THREAD

**Issue by xuedihualu** [zstackorg/zstack#325]
用户的默认策略查不到，还有就是权限支持按照集群或者域划分么

**Comment by youyk** [comment]
默认只读权限策略（Default Read Policy）
当用户被创建时, 一个默认的只读权限策略 (action: .*:read, effect: Allow) 会被挂载到新用户上, 因此用户可以查询资源(例如虚拟机, L3网络).

其他策略可以通过QueryPolicy 来查询。

权限暂不支持按照集群或者域划分。
