### ISSUE TITLE
关闭物理节点后如何才能实现云主机的高可用HA

### ISSUE THREAD

**Issue by sakufo** [zstackorg/zstack#326]
FAQ上提到：
VM高可用在ZStack上，使用共享存储，需要使用cli 先将VM 状态置为stopped， 再次启动此VM，可以在其他节点启动
可是我关闭物理节点后，云主机变的不可操作。
我已经使用NFS共享存储，即使按FAQ上所述能成功也不是自动切换的，zstack是否不能完美支持云主机的故障热迁移？

**Comment by youyk** [comment]
You just need to do a little bit script work to enable the VM HA migration in ZStack. 

After Host is powered off, the VM status can only be changed through zstack-cli . For example, your target VM uuid is abcdefg, and its current status is "unknown". You can do following operations in ZStack management node:

```
 zstack-cli 
#Login system with your ZStack admin password. 
- >>>LogInByAccount accountName=admin password=password
- >>>UpdateVmInstance uuid=abcdefg state=stopped
- >>>LogOut
```

After that, you can start the "stopped" VM in any available host.

**Comment by sakufo** [comment]
非常感谢！
但这样是需要人工干预的，请问zstack目前还无法做到云主机自动切换主机并开启是吗？

**Comment by youyk** [comment]
Yes. ZStack doesn't integrate such kind of solution yet. The key thing is not 'migrating VM', but how to accurately judge if the host lost. There might be hundreds of ways to implement it. But if you are looking for a completed solution, you'd better to visit http://www.mevoco.com -- the enterprise version of ZStack.

**Comment by sakufo** [comment]
I see, thank you！
