### ISSUE TITLE
When I run install-zstack.sh the Command line fail

### ISSUE THREAD

**Issue by SilentTTxo** [zstackorg/zstack#33]
Could not find a version that satisfies the requirement CherryPy==3.2.4 (from zstacklib==0.6) (from versions: )
No matching distribution found for CherryPy==3.2.4 (from zstacklib==0.6) 
but why?

**Comment by youyk** [comment]
Are you able to manually install CherryPy by pip commas?

On Monday, May 25, 2015, SilentTT <notifications@github.com> wrote:

> Could not find a version that satisfies the requirement CherryPy==3.2.4
> (from zstacklib==0.6) (from versions: )
> No matching distribution found for CherryPy==3.2.4 (from zstacklib==0.6)
> but why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/33>.
>


-- 
Yongkang You

**Comment by zxwing** [comment]
It's issue of SSL library of Linux. You need to upgrade the openssl to the latest version
