### ISSUE TITLE
zstack基于块的共享存储的动态迁移，如何保证不损坏文件？

### ISSUE THREAD

**Issue by hipzz** [zstackorg/zstack#330]
如题，zstack底层用的kvm虚拟化，挂载的是iscsi块存储，多主机采用共享存储部署。
那么问题来了，如何保证多主机对于同一文件的写，从而不损坏文件呢？难道kvm有
类似集群文件系统的锁机制？
感谢回答，谢谢！

**Comment by ghxandsky** [comment]
@hipzz ZStack支持SAN存储，通过部署OCFS2共享文件系统支持分布式读写。

**Comment by youyk** [comment]
@hipzz 多机共享SAN存储采用分布式文件系统
