### ISSUE TITLE
iscsiPrimaryStorage: can't determine annotations of missing type org.springframework.util.MimeType

### ISSUE THREAD

**Issue by quarkonics** [zstackorg/zstack#35]
# Environment
zstack version: 0bfddb9162e91d6e56f0c536da67249d5a00ada8
os: ubuntu 14.04
java: java version "1.7.0_75"

# Steps
build command: mvn -DskipTests clean install

# Failure
Error information is as below:
[INFO] iscsiPrimaryStorage ............................... FAILURE [0.429s]
[INFO] mediator .......................................... SKIPPED
[INFO] test .............................................. SKIPPED
[INFO] build ............................................. SKIPPED
[INFO] tool .............................................. SKIPPED
[INFO] doclet ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:01.567s
[INFO] Finished at: Wed Oct 07 04:02:55 CST 2015
[INFO] Final Memory: 96M/684M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.4:compile (default) on project iscsiPrimaryStorage: Compiler errors:
[ERROR] error can't determine annotations of missing type org.springframework.util.MimeType
[ERROR] when processing declare parents MediaType
[ERROR] when weaving intertype declarations MediaType
[ERROR] when processing compilation unit /home/shuang/zstack/zstack/plugin/iscsiPrimaryStorage/src/main/java/org/zstack/storage/primary/iscsi/IscsiBtrfsPrimaryStorageSimulator.java
[ERROR] when batch building BuildConfig[null] #Files=20 AopXmls=#0
[ERROR] [Xlint:cantFindType]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :iscsiPrimaryStorage

# Analysis
If add following content to file zstack/zstack/plugin/iscsiPrimaryStorage/target/classes/META-INF/aop.xml, it would be build successfully:
```xml
<?xml version="1.0"?>
<aspectj>
        <weaver options="-showWeaveInfo">
                <include within="org.zstack.storage.primary.iscsi"/>
        </weaver>
</aspectj>
```

**Comment by zxwing** [comment]
fixed in the mainline
