### ISSUE TITLE
add host failed

### ISSUE THREAD

**Issue by Haomeng** [zstackorg/zstack#36]
I input correct ssh user/password to add host, but get error as below:

REQUEST

{
  "org.zstack.kvm.APIAddKVMHostMsg": {
    "username": "root",
    "password": "kelimeng",
    "name": "host-tw7v",
    "description": null,
    "clusterUuid": "0f486da62f764c589515c5f6a8ce40a1",
    "managementIp": "9.5.127.191",
    "session": {
      "uuid": "5b5752638fad4d20b813615c69621a9c"
    }
  }
}

RESPONSE

{
  "org.zstack.header.host.APIAddHostEvent": {
    "success": false,
    "apiId": "fcd4767ae4914b9abe65edcb3e666a09",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "HOST.1000",
      "cause": {
        "code": "SYS.1000",
        "description": "An internal error happened in system",
        "details": "unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"host\":\"9.5.127.191\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"9-5-127-191.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.6.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.6.tar.gz\"}'] failed\nret code: 3\nstderr: \nstdout: \nPLAY [9.5.127.191] ************************************************************ \n\nGATHERING FACTS *************************************************************** \nfatal: [9.5.127.191] => SSH Error: Permission denied (password,hostbased).\n    while connecting to 9.5.127.191:22\nIt is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.\n\nTASK: [install dependency packages for RedHat based OS] *********************** \nFATAL: no hosts matched or all hosts have already failed -- aborting\n\n\nPLAY RECAP ******************************************************************** \n           to retry, use: --limit @/home/ubuntu/kvm.yaml.retry\n\n9.5.127.191                : ok=0    changed=0    unreachable=1    failed=0   \n\n"
      },
      "description": "Unable to add host",
      "details": "unhandled exception happened when calling private void org.zstack.core.ansible.AnsibleFacadeImpl.1.run(org.zstack.header.core.Completion), \nshell command[sudo ansible-playbook /usr/local/zstack/ansible/kvm.yaml -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"host\":\"9.5.127.191\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"9-5-127-191.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.6.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.6.tar.gz\"}'] failed\nret code: 3\nstderr: \nstdout: \nPLAY [9.5.127.191] ************************************************************ \n\nGATHERING FACTS *************************************************************** \nfatal: [9.5.127.191] => SSH Error: Permission denied (password,hostbased).\n    while connecting to 9.5.127.191:22\nIt is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.\n\nTASK: [install dependency packages for RedHat based OS] *********************** \nFATAL: no hosts matched or all hosts have already failed -- aborting\n\n\nPLAY RECAP ******************************************************************** \n           to retry, use: --limit @/home/ubuntu/kvm.yaml.retry\n\n9.5.127.191                : ok=0    changed=0    unreachable=1    failed=0   \n\n"
    },
    "id": "31334fa1e0f34f34afdefa6540d034a6",
    "creatingTime": 1433764430289
  }
}

**Comment by youyk** [comment]
On Mon, Jun 8, 2015 at 8:06 PM, Haomeng <notifications@github.com> wrote:

> 9.5.127.191


Hi,

Is this machine allowed ssh by "root"?

Could you help to manually rerun following command and check if there is
any valuable information:

/usr/local/zstack/ansible/kvm.yaml -vvv -i /usr/local/zstack/ansible/hosts
--private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/
WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"host\":\"9.5.127.191\",\"
zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"
9-5-127-191.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.6.tar.gz\",\"
pkg_kvmagent\":\"kvmagent-0.6.tar.gz\"}'

-- 
Yongkang You

**Comment by Haomeng** [comment]
Thanks YongKang for your response, yes, the machine can ssh by root.

I try to run the commands with root permision:

ubuntu@ubuntu-14:~$ su - root
Password:
root@ubuntu-14:~# /usr/local/zstack/ansible/kvm.yaml -vvv -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-7.0.35/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\"host\":\"9.5.127.191\",\"zstack_root\":\"/var/lib/zstack/\",\"init\":\"true\",\"hostname\":\"9-5-127-191.zstack.org\",\"pkg_zstacklib\":\"zstacklib-0.6.tar.gz\",\"pkg_kvmagent\":\"kvmagent-0.6.tar.gz\"}'
-su: /usr/local/zstack/ansible/kvm.yaml: Permission denied
root@ubuntu-14:~# ls -l /usr/local/zstack/ansible/kvm.yaml
lrwxrwxrwx 1 zstack zstack 44 Jun  8 06:45 /usr/local/zstack/ansible/kvm.yaml -> /usr/local/zstack/ansible/files/kvm/kvm.yaml
root@ubuntu-14:~# ls -l /usr/local/zstack/ansible/files/kvm/kvm.yaml
-rw-r--r-- 1 zstack zstack 6530 Apr 29 16:12 /usr/local/zstack/ansible/files/kvm/kvm.yaml
root@ubuntu-14:~#

Not sure why it is "Permission denied"?

**Comment by zxwing** [comment]
It doesn't appear in the current mainline
