### ISSUE TITLE
QueryVmInstance  fields=vmNics 查询出错

### ISSUE THREAD

**Issue by Guoozz** [zstackorg/zstack#438]
通过命令行来获取所有虚拟机的网络接口信息，出现如下错误
`API call[org.zstack.header.message.APIReply] failed because [code: SYS.1000, description: An internal error happened in system, details: Can not set java.util.List field org.zstack.header.vm.VmInstanceInventory.vmNics to org.zstack.header.vm.VmNicVO]
API call[org.zstack.header.message.APIReply] failed because [code: SYS.1000, description: An internal error happened in system, details: Can not set java.util.List field org.zstack.header.vm.VmInstanceInventory.vmNics to org.zstack.header.vm.VmNicVO]`
ps: 当`fields=vmNics或allVolumes`查询出错，其他情况没有出现这种情况．

**Comment by youyk** [comment]
请使用 QueryVmNic

如果要查询某个vm的所有网卡：  QueryVmNic vmInstanceUuid=

VmNics 是另外一张表
