### ISSUE TITLE
iscsi volume snapshot revert to volume might fail

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#44]
The failed log is like: 
ApiError: API call[org.zstack.header.storage.snapshot.APIRevertVolumeFromSnapshotEvent] failed because [code: SYS.1006, description: An operation failed, details: subvolume[/home/btrfs/rootVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-0c63876f658741d4841b99bdf5493ed6-by-snapshot/snapshot-d31631687b644bb98810ca585fe39d99] existing]

The reproduce step:
1. Create Data volume and attach to vm
2. Create data volume snapshot1 (sp1) and sp2 sp3,
3. revert data volume to sp1
4. create data volume snapshot1.1 (sp1.1) and sp1.1.2 sp 1.1.3
5. revert data volume to sp1 again
6. try to create new volume snapshot 1.2 will trigger the error .

**Comment by zxwing** [comment]
cdd9d5779ccea851b2aa44728d8c5a1f82f5af22
