### ISSUE TITLE
UI Bug:it does not work when attach data volume to new instance

### ISSUE THREAD

**Issue by qinguanchao** [zstackorg/zstack#5]
When detach a data volume from instance1 and want to attach to instance2,it does not work when operate on UI side but works on zstack-cli;When operates on UI side,it always attach to instance1.

and,on UI side,when want to attach volume from Instances,double click instance name,and click Volume Tab,and select Attach Volume from Actions Menu,there is no data volume listed in box.

**Comment by youyk** [comment]
Thanks for report this bug. It is reproduced. Actually it is a bug in zstack-dashboard. Would you mind close it here and open a new one in zstack-dashboard?

**Comment by youyk** [comment]
This issue might be related with zstck-dashboard:/ts/volume.ts: line 1464:

                    if (vms.length > 0) {
                        this.$scope.vmInstanceUuid = vms[0].uuid;
                    }

**Comment by youyk** [comment]
Open 2 new zstack-dashboard bugs, so close it here. 
https://github.com/zstackorg/zstack-dashboard/issues/2
https://github.com/zstackorg/zstack-dashboard/issues/3
