### ISSUE TITLE
bridge name should be less than 16 chars

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#53]
when create bridge by brctl, the allowed max bridge name length is 15. For example:

brctl addbr br_enp1s0f1_2131
will create bridge : br_enp1s0f1_213

when try to create another bridge: brctl addbr br_enp1s0f1_2132, it will report errors:
device br_enp1s0f1_2132 already exists; can't create bridge with the same name

So, when net device name is longer than 7 chars, we need to shorter it in java side.

**Comment by zxwing** [comment]
fixed in f01b1bcf7104bdf0ef30dafb4364af88badef65b
