### ISSUE TITLE
console fail when zstack dashboard with haproxy

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack#55]
Since the zstack dashboard opens tcp 5000 on private ip, I use haproxy which opens tcp 80 on public ip for port-forward (make it just like public ip on firewall and port forward to internal ip). The web is ok, but it fail to open console. The snapshot as bellow:
![console](https://cloud.githubusercontent.com/assets/2645213/8235994/f00166e8-1617-11e5-8b6e-a43b157b2886.png)

**Comment by zxwing** [comment]
fixed in mainline
