### ISSUE TITLE
URL format hint is wrong for IscsiFileSystemBackendPrimaryStorage

### ISSUE THREAD

**Issue by quarkonics** [zstackorg/zstack#56]
# Environment
zstack versoin: f3ba1dc3f5ab04804802f0db1af01a79e1493f06
zstack dashboard version: 411aca53b3d410a0893dc4f7a99b25f5d96747d6
# Steps
Create primarystorage with type IscsiFileSystemBackendPrimaryStorage
# Failure
There will be hint that URL should be in format of 'ip_or_dns_name:absolute_path', while it actually is 'absolute_path'

**Comment by zxwing** [comment]
fixed in ab01f516e4209b40484298519e9cf239d0d4b2a0 (zstack-dashboard)
