### ISSUE TITLE
IP arrange judgment has bug

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#59]
In https://github.com/zstackorg/zstack/blob/master/network/src/main/java/org/zstack/network/l3/AbstractIpAllocatorStrategy.java, it use string to compare IP range. The string comparison might generate wrong result. For example:
>>> a='192.168.1.1'
>>> b='192.168.1.254'
>>> c='192.168.1.5'
>>> c > a
True
>>> c < b
False

**Comment by zxwing** [comment]
fixed in 91b2a9043d597b835336e1e61ec95d879ae41c90
