### ISSUE TITLE
unable to boot virtual router

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack#6]
I follow the test guid: http://zstack.org/tutorials/ec2-ui.html
When I just craete guest vm, and wait for a long time but throw the respond as bellow: 

{"org.zstack.header.vm.APICreateVmInstanceEvent":{"success":false,"apiId":"54e2cf17dd3a48d98cb0f01f43882a48","headers":{"schema":{}},"error":{"code":"SYS.1006","cause":{"code":"APPLIANCE_VM.1001","description":"Unable to start appliance VM for some reason","details":"\nssh command failed\ncommand: null\nreturn code: 1\nstdout: null\nstderr: null\nexitErrorMessage: Exhausted available authentication methods"},"description":"An operation failed","details":"\nssh command failed\ncommand: null\nreturn code: 1\nstdout: null\nstderr: null\nexitErrorMessage: Exhausted available authentication methods"},"id":"fe36effe71e84098a94935289fc72d7d","creatingTime

**Comment by youyk** [comment]
The VR's boot failure is because the mount time checking mismatch which trigger the manually fsck. 
![image](https://cloud.githubusercontent.com/assets/2962014/7291613/3e063294-e9c5-11e4-995c-ae6e7abbca3f.png)

Will make a new VR image, which will ignore the mount time checking.

**Comment by ghxandsky** [comment]
Thanks, it is resolved.

**Comment by youyk** [comment]
Okay. The issue is because VR booting is blocked by fsck. The fsck is
triggered by "the last mount time is later than current time". Will try to
ignore this error in future VR image.

On Thu, Apr 23, 2015 at 11:25 PM, Star Guo <notifications@github.com> wrote:

> Closed #6 <https://github.com/zstackorg/zstack/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zstackorg/zstack/issues/6#event-288428051>.
>



-- 
Yongkang You
