### ISSUE TITLE
Create VR Offering is better to check L3 network service

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#70]
If L3 select SNAT service, VR Offering's public l3 and management l3 should not select this L3. 

If not do this check, User will add the wrong VR offering wrongly. Then when create the 1st VM, the zstack will report following errors:

![image](https://cloud.githubusercontent.com/assets/2962014/8670108/89d27350-2a4c-11e5-9113-d8c540171438.png)

But if we can detect VR offering adding issue, this could prevent user to see the vm creation errors.

**Comment by zxwing** [comment]
fixed in 207ddda29296c2439068bd4534d5f8c746080b09
