### ISSUE TITLE
PS available capacity is not correct 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#74]
![image](https://cloud.githubusercontent.com/assets/2962014/8713829/9fdd5ab6-2ba0-11e5-8838-0bc1c59dd55f.png)

![image](https://cloud.githubusercontent.com/assets/2962014/8713832/ad952332-2ba0-11e5-8524-923b9424e287.png)

![image](https://cloud.githubusercontent.com/assets/2962014/8713834/bc381796-2ba0-11e5-81cc-02ea200cc620.png)

**Comment by youyk** [comment]
PS capacity does not minus the used space.

**Comment by zxwing** [comment]
fixed in 9868f89b0e1cab19ba6b94100df80babdb3ba1a1 (zstack-utiltiy)
