### ISSUE TITLE
Need set no live snapshot for CentOS 7 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#79]
CentOS7 default qemu doesn't support live snapshot. So we need to disable it by default, no matter the qemu version. 

More information about why CentOS7 doesn't support live snapshot is: https://www.redhat.com/archives/libvirt-users/2014-November/msg00106.html

**Comment by zxwing** [comment]
fixed in bd42bb995038780215eacec6e306170a6aa97f64
