### ISSUE TITLE
VM is not able to be created, if VROffering is not set to isDefault=true

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#87]
If VROffering is not set to is Default=true, creating a new VM will be failed as:
ApiError: API call[org.zstack.header.vm.APICreateVmInstanceEvent] failed because [code: SYS.1006, description: An operation failed, details: unable to find a virtual router offering for l3Network[uuid:01a65b0aefba464db7cde1a642d29def] in zone[uuid:2f091797227d43f0a8350f571a5d8103], please at least create a default virtual router offering in that zone]

Should we allow to use none default VROffering to create VR?

**Comment by zxwing** [comment]
fixed in 8e0d5115922ea45f61d3a0152718255a07044694
