### ISSUE TITLE
create vm fail with ceph ps and sftp bs

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#90]
INFO:zstacklib.utils.http:10.10.3.230 - - [11/Aug/2015:00:48:14] "POST /ceph/primarystorage/sftpbackupstorage/download HTTP/1.1" 200 - "" "Java/1.7.0_85"
WARNING:cephprimarystorage.cephagent:need more than 1 value to unpack
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/cephp/lib/python2.7/site-packages/cephprimarystorage/cephagent.py", line 54, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/cephp/lib/python2.7/site-packages/zstacklib/utils/rollback.py", line 26, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/cephp/lib/python2.7/site-packages/cephprimarystorage/cephagent.py", line 290, in sftp_download
    pool, image_name = self._parse_install_path(cmd.primaryStorageInstallPath)
ValueError: need more than 1 value to unpack

args:[(<cephprimarystorage.cephagent.CephAgent object at 0x2367d90>,

**Comment by youyk** [comment]
This issue happens with sftpbackup storage and ceph primary storage. 

the cmd string：

hMCBPL\nOdE1iASq6oEcM9Co/kNg4TKdtMuAMtuIcjlapo8ZIduR3SRGDw\u003d\u003d\n-----END
 RSA PRIVATE KEY-----","hostname":"10.10.3.230","backupStorageInstallPath":"/home/sftpBackupStorage/rootVolumeTemplates/acct-36c27e8ff05c4780bf6d2fa65700f22e/416b8f6029e2464faf74944d2de11cb0/f18_200m.template","primaryStorageInstallPath":"ceph:///416b8f6029e2464faf74944d2de11cb0","fsId":"bbfcefc0-40db-403f-abce-6cb56f9a3c06","uuid":"11a0e5ce0b044edab54001a77858585d"},{Content-Type=[application/json], Content-Length=[2069], taskuuid=[a3254469e7524859b209edfa8c7c8a4d], callbackurl=[http://10.10.3.230:8080/zstack/asyncrest/callback]}>

**Comment by zxwing** [comment]
fixed in up stream
