### ISSUE TITLE
vm creation failed with both ceph ps and ceph bs

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#91]
<domain type="kvm" xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0"><name>da1ec3b209bc4270bfb74b82689b0b2d</name><uuid>da1ec3b2-09bc-4270-bfb7-4b82689b0b2d</uuid><description>virtualRouter.l3.b7b3ab565a95490399c20f49298d76e4</description><clock offset="utc" /><on_poweroff>destroy</on_poweroff><on_crash>restart</on_crash><on_reboot>restart</on_reboot><metadata><zstack>True</zstack><internalId>2</internalId></metadata><vcpu placement="static">2</vcpu><cputune><shares>1024</shares></cputune><memory unit="k">524288</memory><currentMemory unit="k">524288</currentMemory><os><type>hvm</type><boot dev="hd" /></os><features><acpi /><apic /><pae /></features><devices><emulator>/usr/libexec/qemu-kvm</emulator><input bus="usb" type="tablet" /><interface type="bridge"><mac address="fa:b1:c7:d9:5f:00" /><alias name="vnic2.0" /><source bridge="br_eth0.103" /><model type="virtio" /><target dev="vnic2.0" /></interface><interface type="bridge"><mac address="fa:09:a3:93:d1:01" /><alias name="vnic2.1" /><source bridge="br_eth0_21" /><model type="virtio" /><target dev="vnic2.1" /></interface><disk device="disk" type="network"><source name="pri-v-r-6770bce004364e7c897ec074acbe3b2b/9f4594df7e00499a8292562987e67f72" protocol="rbd"><host name="ceph1" port="6789" /><host name="ceph2" port="6789" /><host name="ceph3" port="6789" /></source><auth username="zstack"><secret type="ceph" uuid="1b148989-5e9a-3200-a995-253af6c4cd45" /></auth><target bus="virtio" dev="vda" /></disk><graphics autoport="yes" port="5900" type="vnc"><listen address="0.0.0.0" type="address" /></graphics><channel type="unix"><source mode="bind" path="/var/lib/zstack/kvm/agentSocket/applianceVm.da1ec3b209bc4270bfb74b82689b0b2d" /><target name="applianceVm.vport" type="virtio" /></channel></devices></domain>

2015-08-11 01:18:02,379 WARNING [vm_plugin] Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1371, in _start_vm
    vm.start(cmd.timeout)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 493, in start
    self.domain.createWithFlags(0)
  File "/usr/lib64/python2.6/site-packages/libvirt.py", line 716, in createWithFlags
    if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
libvirtError: Unable to read from monitor: Connection reset by peer

2015-08-11 01:18:02,380 WARNING [vm_plugin] Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1411, in start_vm
    self._start_vm(cmd)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1374, in _start_vm
    raise kvmagent.KvmError('unable to start vm[uuid:%s, name:%s], libvirt error: %s' % (cmd.vmInstanceUuid, cmd.vmName, str(e)))
KvmError: unable to start vm[uuid:da1ec3b209bc4270bfb74b82689b0b2d, name:virtualRouter.l3.b7b3ab565a95490399c20f49298d76e4], libvirt error: Unable to read from monitor: Connection reset by peer

**Comment by zxwing** [comment]
invalid use of centos 6.6
