### ISSUE TITLE
Delete Image won't cleanup rbd in Ceph BS pool

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#93]
Reproduce step:
1. create vm1 and stop vm1
2. use vm1's root volume to create template image
3. use template image to create vm2.
4. destroy vm1, vm2, and delete new created template image.
5. check the template image in bs ceph (rbd info), it is still alive.

**Comment by zxwing** [comment]
the image won't be deleted until no vms refer to it. The mechanism of cpeh backup storage is different than others. When downloading a template from ceph backup storage to ceph primary storage, the actual action is to clone a new image from it. So deleting image won't delete it on backup storage until there is no vms use it, then the garbage collector will clean it
