### ISSUE TITLE
Can NOT acquire the lock again before unlock, GLock is non reentrant

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#96]
In 0.9 upstream, when creating multi vm with VR service at the same time might meet following error:

ApiError: API call[org.zstack.header.vm.APIStartVmInstanceEvent] failed because [code: VM.1001, description: Unable to start a vm, details: unhandled exception happened when calling public void org.zstack.network.service.virtualrouter.VirtualRouterManagerImpl.acquireVirtualRouterVm(org.zstack.network.service.virtualrouter.VirtualRouterStruct, org.zstack.header.core.ReturnValueCompletion), Thread[zs-thread-26] has acquired lock[glock-vr-l3-0f6bed5d416c42a89900433a15f24657], you can NOT acquire the lock again before unlock, GLock is non reentrant]

**Comment by zxwing** [comment]
fixed in 2b8da58a52efb4f31e19f57d35c1cc4c2773b3af
