### ISSUE TITLE
Query API with multiple conditions might return wrong result

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#98]
Test environment:
1, 0.9 upsteam
2, **management l3 and public l3 share same public l3**
3, **public l**3 is not system l3 and has **DHCP and DNS services**
4, there are other private l3 and has SNAT services, which will create VRs.

reproduce step:
1. create private l3 vms and public l3 vm, this will create a serial of VR VMS. 
2. in zstack-cli, query VR (applianceVm) which using l3=public_l3_uuid as private l3, but not only public l3.
3, if the query api is like following line, the return result is just 1 VR (public l3 VR).
QueryApplianceVm vmNics.l3NetworkUuid?=95b46bc1a8fe4ffdac5638d20f0a8764 vmNics.metaData!=3 vmNics.metaData!=2 vmNics.metaData!=1
4, but if the query api is like following line, the return result includes 3 VRs.
QueryApplianceVm vmNics.l3NetworkUuid?=95b46bc1a8fe4ffdac5638d20f0a8764 vmNics.metaData!=1 vmNics.metaData!=2 vmNics.metaData!=3

**Comment by youyk** [comment]
After tracking mysql.log, this issue should be a bug in query api code:
If the condition key is same, the query API will use the 1st data number, no matter how many data numbers are provided:
where (vmnicvo1_.l3NetworkUuid in ('90cd54d7d69a4a0cbb58c3cc9c9bdef0')) and vmnicvo1_.metaData<>'3' and vmnicvo1_.metaData<>'3' and vmnicvo1_.metaData<>'3') limit 1000

**Comment by zxwing** [comment]
fixed in 752cccd47f13c2ceeb760fd580843ce303e1b6d0
