### ISSUE TITLE
VM migration failed if using ceph ps

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#99]
ApiError: API call[org.zstack.header.vm.APIMigrateVmEvent] failed because [code: HOST.1009, description: Failed to migrate vm on hypervisor, details: failed to migrate vm[uuid:89a23d3d3d9c45f29c4c1eb11b0168ff] from kvm host[uuid:0bd71456fd524f479e2439bef3f59216, ip:10.10.2.241] to dest host[ip:10.10.2.242], unable to migrate vm[uuid:89a23d3d3d9c45f29c4c1eb11b0168ff] to qemu+tcp://10.10.2.242/system, Secret not found: rbd no secret matches uuid 'fd88ccde-1037-4795-8306-4b0adfdc57fa']

**Comment by zxwing** [comment]
fixed in 53e11fccbdeaf1cd2604abc987e162b267376af0
